=== Chapter 12: Complexity, chaos and the road ahead

==== Introduction to chapter 12

As we look forward, and consider the scale at which we are now operating, the challenges only seem to increase. Increasingly, we need to look to engineering and operations practices from other fields, and to math and science for useful theoretical tools.

Risk management, complex systems failures, how to safely manage combined human/technical systems - this is all well studied in domains like aerospace. We can't understand "change" management without better definitions of change and stability, concepts well studied in the quantitative sciences. No matter the safeguards, complex systems are prone to fail - but can we conceive of systems that can increase their stability through learning from their failures?

Finally, what do we even mean by complexity? What is the relationship between the merely complicated, the truly complex, and the absolutely chaotic? What do we need to understand about these various domains, to continue our journey of digital transformation?

===== Chapter 12 outline

****
Sidebar: Introducing Burgess.
****

* complexity (w/r/t Burgess)

* stability, state, etc

* complex system failures (Allspaw sidebar?)

* antifragility

* Cynefin

* self-steering, autopoeisis

* post-industrial

* Postscript: Thought experiment on complete mainstreaming of IT

****
Sidebar: Introducing Snowden & Taleb.
****

===== Learning objectives

* Identify current approaches to understanding complex systems and their failure modes

* Describe Snowden's Cynefin and its major elements
