==== Defining consumer, customer, and sponsor

In understanding IT value, it is essential to clarify the definitions of user, customer, and sponsor. Sometimes, the user *is* the customer. But more often, the user and the customer are different, and one may additionally need to distinguish the role of system or service sponsor.

The following definitions may help

* The *consumer* (sometimes called the *user*) is the person actually interacting with the IT-based service.
* The *customer* is source of revenue for the service. If the service is part of a profit center, the customer is the person actually purchasing the product (e.g. demand deposit banking.) If the service is part of a cost center (e.g. an HR system), the customer is best seen as an internal executive, as the actual revenue-producing customers are too far removed.
* The *sponsor* is the person who authorizes and controls the funding used to construct and operate the service.

Depending on the service type, these roles can be filled by the same or different people. Here are some examples:

[cols="5*", options="header"]
|====
|Example |Consumer |Customer |Sponsor |Notes
|Online banking 2+^|Bank account holder | Vice president, consumer banking | Customer-facing profit center with critical digital component
|Online restaurant reservation application |Restaurant customers |Restaurant owners |Product owner | Profit-making digital product
|Enterprise human resources application |HR analyst 2+^|Vice president, HR | Cost center funded through corporate profits
|Online video streaming service |End video consumer (e.g. any family member) |Streaming account holder (e.g. parent) |Streaming video product owner | Profit-making digital product
|Social traffic application | Driver | Advertiser, data consumer | Product owner |
|====

So, who paid for our user's enjoyment? The bank and restaurant both had clear motivation for supporting a better online experience, and people now expect that service organizations provide this. The bank experiences less customer turnover and increased likelihood that customers add additional services. The restaurant sees increased traffic and smoother flow from more efficient reservations. Both see increased competitiveness.

The traffic application is a somewhat different story. While it is an engineering marvel, there is still some question as to how to fund it long term. It requires a large user base to operate, and yet end consumers of the service are unlikely to pay for it. At this writing, the service draws on advertising dollars from businesses wishing to advertise to passersby, and also sells its real-time data on traffic patterns to a variety of customers, such as developers considering investments along given routes.

This last example well illustrates the maxim that "if you don't know how the product is making money, you are the product."

ifdef::collaborator-draft[]

_Collaboration notes_

_todo: let's put in basic impact mapping here_

_-ctb_

endif::collaborator-draft[]

****
*IT exists in a social context*

Like the proverbial fish that doesn't understand water (because water it all it knows), we may lose sight of the laws and customs that enable us to use computers in the ways covered in this chapter.

For example, the ability for banks to hold money as electronic bits on a computer is rooted in the earliest history of banking and the emergence of centralized settlement and clearing mechanisms. Cell phone companies rely on international treaties, and national laws and regulations allocating radio spectrum.

The existence of physical voice and data connectivity relies on laws supporting utility easements and rights of way, and even treaties such as the Law of the Sea (how is it that undersea cables remain unmolested?).

In short, without a social infrastructure, social and collaborative technology has no meaning.
****
