=== Chapter 6: Operations Management

ifdef::instructor-ed[]

****
_Instructor's note_

Although this is entitled "operations management" it also brings in infrastructure engineering at a higher level, assuming that the product is continuing to scale up. Chapter 12 will revisit infrastructure engineering and operations in terms of the most highly scaled and complex Web-scale systems.

Thus, Chapters 2, 6, and 12 constitute a sort of "infrastructure and operations" track within the book.

****
endif::instructor-ed[]

==== Introduction to Chapter 6

As your product gains more use, you find that running it inevitably becomes a distinct concern from building it. For all their logic, computers are still surprisingly unreliable. Servers running well tested software that remain "up" for weeks all of a sudden hang and have to be rebooted. Sometimes it's clear why (for example, a log filled up that no-one expected) and in other cases there just is no explanation.

Engineering and operating complex IT-based distributed systems is a significant engineering challenge. Even with infrastructure as code, it is distinct from software development per se. Quesions of scalability, performance, caching, load balancing, and so forth usually become apparent first through feedback from the operations team.

****
Sidebar: Introducing Limoncelli.
****

===== Chapter 6 outline

* Defining "operations"

* Kinds of work (where is that original concept)
 - interrupt-driven
 - etc

* Event management and monitoring

* Capacity and performance management

* Incidents, disasters, and everything in between

 * Impact & dependency

****
Sidebar: Configuration Management and the CMDB
****

* State & stability (Burgess?)

* Control theory?

* Web-scale IT (first pass)

* Antifragility
 - Chaos bestiary


===== Chapter 6 learning objectives

* Distinguish kinds of work, esp operational vs development
* Describe operational feedback into product design & the kinds of concerns it raises
* Describe impact and dependency analysis and why it is important


Increasingly, as operational performance is defined in code (the trend to Infrastructure as Code), operational issues are equivalent to development defects.
