==== Conclusion
While operations management is an integral part of "DevOps," and of a given product's management, it is still a distinct area of concern and practice. The focus on interrupt-driven work results in different personality types being attracted to it, and different management approaches required.

Operations management has a broader industry meaning, but in the narrower IT sense, includes concerns of monitoring, state and configuration management, capacity and performance concerns, and related topics.

===== Discussion questions
* Have you or anyone you've known worked in a call center or operations center? What was it like?
* Do you prefer interrupt-driven or focused development work?

===== Research & practice
* Stand up two VMs, one with a web server, the other with Nagios or another open-source monitoring tool. Experiment with monitoring various aspects of the web server.

* In a team kanban setting, experiment with both user stories and operations requests coming into the same board or product team. What issues arise? How can you best handle the diversity of work? What if there were 10 times as much, what would you do?

===== Further reading

* Thomas A. Limoncelli, Strata R. Chalup, Christina J. Hogan, http://www.goodreads.com/book/show/23131211-the-practice-of-cloud-system-administration[The Practice of Cloud System Administration: Designing and Operating Large Distributed Systems, Volume 2]
* John Allspaw, http://www.goodreads.com/book/show/8571725-web-operations[Web Operations: Keeping the Data On Time]



===== Articles/posts

https://aws.amazon.com/message/5467D2/?utm_content=buffer72a89&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer[AWS DynamoDB Fall 2015 outage]

http://techironic.com/post/129767406981/the-truth-behind-building-multiple-environments-to[The truth behind building multiple environments to run your services]

http://csel.eng.ohio-state.edu/woods/design/concepts/nav_problems.pdf[Orienting in Virtual Perceptual Fields]

http://www.allofe.com/gen/corp_generated_bin/documents/basic_module/designing1.pdf[http://www.allofe.com/gen/corp_generated_bin/documents/basic_module/designing1.pdf]

http://techblog.netflix.com/2011/07/netflix-simian-army.html[The Netflix Simian Army]
