==== Introducting Operations Management

What do we mean by operations? Operations management is a broad topic in management theory, with whole programs dedicated to it.

We started to run into this in chapter 5, as we examined the topic of “work management” - in traditional operations management, the question of work is primary. However, in IT, “operations” tends to have a narrower meaning, being focused on the immediate questions of systems availability and performance trending.

Operations often can mean, “everything but development” in an IT context. When merged with IT into “DevOps,” one gets IT Product Management with an Agile twist. We will take a close look at the various aspects of IT operations in this chapter.
Consider the following various definitions of “operations” in an IT context. Some are relevant to our “two pizza team” scenario, some might be more applicable to larger environments:

* Keeping track of an IT product’s availability (is the Web site working?), and troubleshooting if it goes down (e.g. by rebooting it).
* Answering phone calls from users requiring support. They may be calling because a system or service they need is malfunctioning. They may also be calling because they do not understand how to use the system for the value experience they have been led to expect from it.
* Physically traveling to a remote site to evaluate and if necessary update or fix IT hardware and/or software.
* Performing routine work, such as installing hardware, granting access, or running or testing backups. Such routine work may be scheduled, or it may be on request (e.g. ticketed).
* Ensuring security protocols are followed, e.g. access controls.

As above, the primary thing that operations does NOT do is develop new systems functionality. However, new functionality usually has operational impacts.

It used to be that development was a minority of work, while operations was where the bulk of work happened. However, when an operational task becomes repetitive and risk-free, it can be automated. This continuous cycle of innovation and commoditization has driven closer and closer ties between “development” and “operations.” It also has driven confusion around exactly what is meant by “operations.”

In many organizations, there is an “Infrastructure and Operations” function. Pay close attention to the naming. A matrix may help, because we have two dimensions to consider here.

[cols="3*", options="header"]
|====
||Development phase
|Operations phase
|Application layer
|Application developers. Handle demand, proactive and reactive, from product and operations.
|Help desk. Application support and maintenance (provisioning, fixes not requiring software development).
|Infrastructure layer
|Engineering team. Infrastructure platform engineering and development (design and build typically of externally sourced products)
|Operations center. Operational support, including monitoring system status. May monitor both infrastructure and application layers.
|====
