== Section I: Inception

This is the introduction to Section I.

In this section, we  explore the fundamentals of information technology delivery.

Scenario: You are working in a startup, alone or with one partner. You are always in the same room, easily able to carry on a running conversation about your efforts and progress. You have no time or resources to spend on anything except keeping your new system alive and running.

=== Chapter 1: IT Value
Chapter 1 introduces you to the fundamental concepts of IT value that serve as a basis for the rest of the course. Why do people want computing (IT) services? What are the general outlines of their structure? How do they come into being? How are they changed over time?

All of this is essential to understand for your scenario; you need to understand what computers can do and how they are generally used, if you are going to create a product based on them.

This chapter also covers the basics of how you'll approach building a product. It's assumed you won't develop an intricate, long-range plan but rather will be experimenting with various ideas and looking for "fast feedback" on their success or failure.

=== Chapter 2: IT Infrastructure
In this chapter, you have a general idea for a product and are ready to start building it. But not so fast... you need to decide some fundamentals first. How will your new product run? What will you use to build it? It's not possible to begin construction until you decide on your tools. This chapter will provide you an overview of computing infrastructure including Cloud hosting and various approaches to system construction.

=== Chapter 3: Application delivery


=== This section's lab approach

While this is not a book about any particular computing language or platform, we need to describe some technical fundamentals. We’ll do so in as neutral a manner as possible. However, the specific technologies employed in this books’ accompanying labs are based on Ubuntu Linux and git, the distributed version control system created by Linus Torvalds to facilitate Linux development.
