== README -- Agile IT management: from startup to enterprise

:toc:


_Note, if you came to this via the Github repository (https://github.com/dm-academy/aitm), you might want to look at the content which is now being rendered to http://dm-academy.github.io/aitm/[Github Pages]. Same stuff, but more navigable and the whole book will be there. If you're already on Github Pages (http://dm-academy.github.io/aitm/) never mind._

Welcome to Agile IT Management, the first general, survey-level text on IT management written from an Agile and Lean IT perspective.

=== Views on the book

There are three main views on the book:

* The http://dm-academy.github.io/aitm/[Student Edition]

* The http://dm-academy.github.io/aitm/aitm-instructor.html[Instructor's Edition], with commentary, background, and additional resources intended for instructors using the book in their class

* The http://dm-academy.github.io/aitm/aitm-collaborator.html[Collaborative Draft], including the content of both editions, work in process, and collaborative discussion

All are generated from the same source files. Include macros are used to include the additional instructor commentary.

=== Participating

I need reviewers and content contributors. I especially appreciate well-informed sidebars on specific topics and will give full in-text authorial credit for such. Or, you can help with the body of the text. I also want to cultivate an ecosystem of labs, but that is a different story.

My desire is that interested parties contribute to this project via standard Github techniques. I realize this places a barrier for some otherwise qualified contributors. However, I believe that *source control is a singularly important practice*; it is the constraint which enables much of the benefits of Agile.

Learning Github is a good use of your time, if you seek to teach the next generation of IT practitioners. They are heading out into a world of "infrastruture as code" and pervasive use of source control. Github portfolios are increasingly selection criteria in the hiring process for IT professionals.

(Of course, if you have a nice standalone sidebar, or a *few* random edits, send them on to me however and I can work them in.)

In terms of an Agile medium, the format of the book on Github will allow for better "random access" reviewing. This I think will be an improvement over the standard "read a big batch of my work please." I'll point to specific sections as they are completed, and as discussions progress on Twitter & other channels, an approach I think is more agile.

I will say more about the labs elsewhere, but I have found that developing good labs is extraordinarily labor-intensive. I intend that each chapter have a solid lab (or multiple alternatives) and would greatly value any contributions that align with the book's progression.

=== The road ahead

I have not decided on a publishing channel. I am experimenting with LeanPub, but the final decision is pending. The work would always be free here, but I may put additional formatting work in and sell the resulting value-added product. I am  considering setting up a nonprofit of some sort to further the work. And I am still considering the licensing options. Interested in any ideas along these lines.

My stance on these issues depends directly on other people making substantial contributions. If that does not happen, I will consider other, more proprietary models, although I remain concerned for educational access and am not inclined to publish this solely as a $150.00 glossy textbook.

If you have comments or questions, please log a https://github.com/dm-academy/aitm/issues[Github issue] on this repository. Or drop me a line at char AT dm-academy DOT com.

=== Progress notes

_7/23/2015 Work in progress: I am moving most of this README to the http://dm-academy.github.io/aitm/#_preface[preface], but there will remain a placeholder w/pointers here._

Status as of 7/16/2015: I have ~60,000 words in Scrivener that I am starting to transfer to Github. This is not a simple conversion, the material needs further rewriting as I do this. But this project is by no means starting from scratch. Stop back in a few weeks and you'll see actual content.

Updated status as of 8/6/2015: Have a complete file system and placeholder files, first 2 chapters are reasonable first drafts, working on Chapter 2.

_End of README, beginning of actual book build._
