==== Examining an IT value experience

===== The "IT stack"

===== The "IT service"

===== The IT service changes over time

===== The IT service lifecycle

But who paid for our user's enjoyment? The bank and restaurant both had clear motivation for supporting a better on line experience, and people now expect that service organizations provide this. The bank experiences less customer turnover and increased likelihood that customers add additional services. The restaurant sees increased traffic and smoother flow from more efficient reservations. Both see increased competitiveness.

The traffic application is a somewhat different story. While it is an engineering marvel, there is still some question as to how to fund it long term. It requires a large user based to operate, and yet end users are unlikely to pay for it. At this writing, the service draws on advertising dollars from businesses wishing to advertise to passersby, and also sells its real-time data on traffic patterns to a variety of customers, such as developers considering investments along given routes.




   [for next chap?]
So, what is IT value? I suggest the following:

IT Value is found in qualifying the organization or individual to participate effectively (maximize utility, in economic terms) in information-rich environments. If the situation is competitive, it also consists of elevating their performance above peers.
