== Section I: Inception

This is the introduction to Section I.

In this section, we  explore the fundamentals of information technology delivery.

*Scenario*

You are working in a startup, alone or with one or two partners. You are always in the same room, easily able to carry on a running conversation about your efforts and progress. You have no time or resources to spend on anything except keeping your new system alive and running.

*Chapter 1: IT Value*

Chapter 1 introduces you to the fundamental concepts of IT value that serve as a basis for the rest of the course. Why do people want computing (IT) services? What are the general outlines of their structure? How do they come into being? How are they changed over time?

All of this is essential to understand for your scenario; you need to understand what computers can do and how they are generally used, if you are going to create a product based on them.

This chapter also covers the basics of how you'll approach building a product. It's assumed you won't develop an intricate, long-range plan but rather will be experimenting with various ideas and looking for "fast feedback" on their success or failure.

*Chapter 2: IT Infrastructure*

In this chapter, you have a general idea for a product and are ready to start building it. But not so fast... you need to decide some fundamentals first. How will your new product run? What will you use to build it?

It's not possible to begin construction until you decide on your tools. This chapter will provide you an overview of computing infrastructure including Cloud hosting and various approaches to system configuration.

This chapter also presents an overview of source control, as even your infrastructure depends on it in the new world of "infrastructure as code."

*Chapter 3: Application delivery*

Finally, you're ready to start building something. While this is not a book on software development or programming languages, it's important to understand some basics and at least see them in action.

This is also the "DevOps" chapter; it's not just about writing code, but about the entire end to end system that gets the code you are writing from your workstation, into collaborative environments, and finally to a state where it can be accessed by end users. From source repository to build manager to package repository to production, we'll cover a basic toolchain that will help you understand modern industrial practices.

*This section's lab approach*

While this is not a book about any particular computing language or platform, we need to describe some technical fundamentals. We’ll do so in as neutral a manner as possible. However, this books’ accompanying labs are based on http://www.ubuntu.com/[Ubuntu Linux] and https://git-scm.com/[git], the distributed version control system created by Linus Torvalds to facilitate Linux development.
