=== Chapter 11: Enterprise Information Management

==== Introduction to Chapter 11

 [todo: write EIM intro]

 [next material is EIM applied to IT, keep but reduce scope/importance somewhat - should still be a major chapter section]

 Analytics and metrics are a related topic for IT management. There are many ways that metrics can be used and misused. A clear understanding of organizational goals is essential to any metrics strategy. Analytics similarly requre an overall framework of continuous improvement so that their insights lead to real actions and value.

IMPORTANT: As with other chapters in the later part of this book, we are going to introduce this topic "on its own terms." We will then add additional context and critique in subsequent sections.

===== Chapter 11 outline

* Big data and digital management - each apply to the other - two sides of the coin -

* Defining "analytics"


* The enterprise information model: a failed vision that will never go away.


* ontologies. Problems in developing them. BORO, OPAL, CACM 3/16 article on lightweight ontology engineering.

* IT analytics
 - grounded in continuous improvement
 - Portfolio and process data
 - The IT data warehouse
 - Looking ahead: Big Data, machine learning, text analytics

===== Data, information, knowledge

===== The ontology problem
OPAL, BORO, etc

BoundedContext and domain-driven design



===== Records vs data

===== input material

http://searchcio.techtarget.com/definition/agile-business-intelligence-BI?utm_medium=EM&asrc=EM_NLN_56914325&utm_campaign=20160510_Word%20of%20the%20Day:%20Agile%20business%20intelligence%20(BI)_kherbert&utm_source=NLN&track=NL-1823&ad=907631&src=907631
