==== Introducing Scrum

[quote, Chris Sims/Hillary L. Johnson, Scrum: A Breathtakingly Brief and Agile Introduction]
Scrum is a lightweight framework designed to help small, close-knit teams of people develop complex products.

[quote, Jeff Sutherland, Scrum: The Art of Doing Twice the Work in Half the Time]
There Are No Tasks; There Are Only Stories.

One of the first Agile methodologies you are likely to encounter as a practitioner is Scrum. There are many books, classes, and websites where you can learn more about this framework; <<Sims2012>> is a good introduction.

We mention Scrum in this chapter, as it is very product-focused. It calls for the roles of

* Product owner
* Scrum master
* Team member

and avoids further elaboration of roles.

The Scrum product owner is responsible for seeing that the team executes the highest value work. To do this, the potential features for the product are maintained in a "backlog" that can be re-prioritized as necessary (rather than a large, fixed-scope project).
