=== Chapter 4: Product Management

==== Introduction to Chapter 4

****
*Product Management?*

"Product management?" In a book on IT management? Those of you with industry experience, especially backgrounds in project-based enterprise software development, may be unfamiliar with the term. However, a focus on product development is one of the distinguishing features of Agile development, even if that development is taking place in a larger enterprise context.
****

As you grow your company, you are bringing more people in. You become concerned that they need to share the same vision that inspired you to create this company. This is the goal of product management.

Product strategy was largely tacit in Section I. Need more formalized approaches to defining, communicating, executing.

Furthermore, while we covered Agile principles and practices in some detail last chapter, we did not discuss *why* they work. In this chapter, we will cover the Lean theory of product management that provides a basis for Agile practices, in particular the work of Don Reinertsen.

===== Chapter 4 outline

* Why product management
** The role of the product owner.
* Product design
** Lean Startup
** LeanUX and Continuous Design.
** Behavior-driven development.
* Scrum
* Lean, Lean Product Development, and Don Reinertsen.
** Lean manufacturing vs Lean product development
** Applicability to IT
* Reinertsen
** Pyramid
** Importance of small batch sizes
** Product development as creation of information
** Cost of Delay

===== Chapter 4 learning objectives

* Define and distinguish product versus project management
* Define and distinguish Lean manufacturing versus Lean product development
* Describe key principles of user experience (UX) and behavior-driven development
* Describe relationship between small batch sizes, limited work in process and fast feedback
