==== Product Design

[quote, Jeff Sussna]
Design thinking is changing an existing to a preferred state...

Now that we have surveyed the overall field of product management, we can turn more specifically to the topic of product design.

The presence of a section entitled "product design" in this book is a marked departure from other IT management textbooks. "Traditional" models of IT delivery focus on projects and deliverables, concepts we will not explore until chapter 8.

However, the ideas of projects and deliverables represent approaches that are more open-loop, or at least delayed in feedback. Design processes do not perform well when feedback is delayed.

===== Lean Startup
[quote, Eric Ries, The Lean Startup]
...some Ries quote here

Lean Startup is a philosophy of entrepreneurship developed by Eric Ries <<Ries2011>>. It is not specific to information technology; rather, it is broadly applicable to all attempts to understand a product and its market. (Remember according to our definition that a workable market position is essential to any product.)

The idea of the Lean Startup has had profound influence on product design, including market-facing and even internal IT systems. It is grounded in Agile concepts such as

"Do the simplest thing that could possibly work."

Lean Startup calls for an iterative, "Build-Measure-Learn" cycle. Repeating this cycle frequently is the essential process of building a successful startup (whatver the digital proportion).

* Develop an idea for a Minimum Viable Product


*Limitations of Lean Startup philosophy*

===== LeanUX and Design Thinking

===== Tracking product decisions

===== Features vs. components

As your product evolves, you may see an increasing differentiation of concerns, between features and components.

Features are what your product *does*. They are what the customers perceive as valuable.

“Scope as viewed by the customer” (*** Kennaley sdlc 3.0, p169)

Components are how your product is built, such as database vs. Web components.

Feature teams are dedicated to a clearly defined functional scope, while component teams are defined by their technology platform. Component teams may become shared services, which need to be carefully understood and managed (more on this in Section 3).

It may be easy to say that features are more important than products, but this can easily be carried too far. Do you want each feature team choosing its own database? Not recommended. Allowing feature teams to define their own technical direction can result in brittle, fragmented architectures, technical debt, and rework.

Software product management needs to be a careful balance between these two perspectives. Some recommend a ratio of 70-80% Feature teams to 20-30% Component teams  (http://blog.octo.com/en/feature-team-beyond-the-buzzword/).

http://blog.octo.com/en/feature-team-beyond-the-buzzword/
http://scaledagileframework.com/features-components/

Spotify also uses “client app” squads.

We will be revisiting this more systematically in chapter 7.


===== Software and systems engineering
Some of the most contentious discussions related to IT management and Agile come at the intersection of software and systems engineering, especially when large investments are at stake.

We will
