==== Why Product Management?

Before work, before operations, there must be a vision of product. You already established a preliminary vision in Chapter 1, but now as your organization grows, you need to consider further how you will sustain that vision and establish an ongoing flow of work to realize it.

Like many other topics in this book, product management is a significant field in and of itself. Historically, product management has not been a major theme in enterprise IT management. "Third party" vendors (e.g. IBM) providing the back office systems had product management approaches, but these were external to the IT operations.

IT systems served narrow purposes, often “back office” functions such as accounting or materials planning. Mostly, such systems were managed as projects assembled on a temporary basis, resulting in the creation of a system to be “thrown over the wall” to operations.

Product management, on the other hand, is concerned with the entire lifecycle. The product manager cares about the vision, its execution, the market react ion to the vision (even if an internal market), the health, care and feeding of the product, and the product’s eventual sunset or replacement.

Reacting to market feedback and adapting product direction is an essential role of the product owner. In the older model, feedback was often unwelcome, as the project manager typically was committed to the open-loop dead reckoning (see http://dm-academy.github.io/aitm/#_special_section_systems_thinking_and_feedback[previous discussion]) of the project plan and changing scope or direction was seen as a failure, more often than not.

Now, it’s accepted that systems evolve, perhaps in unexpected directions. Rapidly testing, learning, failing fast, and pivoting direction are all part of the lexicon, at least for market-facing IT-based products. And even back-office IT systems with better understood scope are being managed more as systems (or products) with lifecycles, as opposed to transient projects.

So, what is product management and what does it mean for your team?

===== Defining Product Management

In order to define product management, we first need to define product. In Chapter 1, we established that products are goods, services, or some combination, with some feature that provides value for some consumer. BusinessDictionary.com http://www.businessdictionary.com/definition/product.html[defines it thus]:

[quote, BusinessDictionary.com]
[A Product is] A good, idea, method, information, object or service created as a result of a process and serves a need or satisfies a want. It has a combination of tangible and intangible attributes (benefits, features, functions, uses) that a seller offers a buyer for purchase. For example a seller of a toothbrush not only offers the physical product but also the idea that the consumer will be improving the health of their teeth…A good or service that most closely meets the requirements of a particular market and yields enough profit to justify its continued existence. As long as cars are manufactured, companies such as Michelin that produce tires fill the market need and continue to be profitable.

Product _management_, according to the http://www.businessdictionary.com/definition/product-management.html#ixzz3bHCVkoWj[same source], is

[quote, BusinessDictionary.com]
[Product Management is] The organizational structure within a business that manages the development, marketing and sale of a product or set of products throughout the product life cycle. It encompasses the broad set of activities required to get the product to market and to support it thereafter.

Product management in the general sense often reports to the Chief Marketing Officer (CMO). It represents the fundamental strategy of the firm, in terms of its value proposition and viability.

As a field, there are professional associations, handbooks, courses of study, and so forth, completely independent of information technology.

However, http://dm-academy.github.io/aitm/#_defining_information_technology[as stated in chapter 1], all kinds of industrial products have increasing amounts of “IT” in them. This means that an understanding of IT, and ready access to any needed IT specialty skills, is increasingly important to the general field of product management.

===== Product vs project management

Here are some of the key differences between project and product management:



Project
Product
Limited time duration, often scoped to a year or less
No specific time duration; lasts as long as there is a need
Difficult to change scope or direction, unless specifically set up to accommodate
Better accommodates market feedback and directional change
Often concerned with the design and construction, but typically not with operating
Includes concept, design, construction, operations, and retirement
Project managers are trained in resource and timeline management, dependencies & scheduling. They are not typically incented to adopt a long-term perspective.
Product managers need to have project management skills as well as understanding market dynamics, feedback, building long-term organizational capability
Projects can be planned with a high degree of certainty
Product management includes research and development which is less certain of outcome



In our scenario, you are now on a tight-knit, collaborative team. It is preferable that you think in terms of developing and sustaining a product. However, projects still exist, and sometimes you may find yourself on a team that is funded and operated on that basis.
