==== Product design

[quote, Herbert Simon]
Everyone designs who devises courses of action aimed at changing existing situations into preferred ones.

[quote, Jacques Murphy, Pragmatic Marketing]
 What is a Product Manager? A Product Manager is the one person in the whole organization who owns the product Requirements effort. Requirements focuses on the WHAT, which means it isn't Development, which focuses on the HOW. And Marketing traditionally talks about the WHAT, but cannot necessarily decide what the WHAT should be. At least not at any useful level of detail.

Now that we have surveyed the overall field of product management, we can turn more specifically to the topic of product design.

The presence of a section entitled "product design" in this book is a marked departure from other IT management textbooks. "Traditional" models of IT delivery focus on projects and deliverables, concepts we will not explore until chapter 8.

However, the ideas of projects and deliverables represent approaches that are more open-loop, or at least delayed in feedback. Design processes do not perform well when feedback is delayed.

===== Lean Startup
[quote, Eric Ries, The Lean Startup]
The goal of a startup is to figure out the right thing to build— the thing customers want and will pay for— as quickly as possible. In other words, the Lean Startup is a new way of looking at the development of innovative new products that emphasizes fast iteration and customer insight, a huge vision, and great ambition, all at the same time.

Lean Startup is a philosophy of entrepreneurship developed by Eric Ries <<Ries2011>>. It is not specific to information technology; rather, it is broadly applicable to all attempts to understand a product and its market. (Remember according to our definition that a workable market position is essential to any product.)

The idea of the Lean Startup has had profound influence on product design, including market-facing and even internal IT systems. It is grounded in Agile concepts such as:

"Do the simplest thing that could possibly work."

Lean Startup calls for an iterative, "Build-Measure-Learn" cycle. Repeating this cycle frequently is the essential process of building a successful startup (whatever the digital proportion).

* Develop an idea for a Minimum Viable Product (MVP)
* Measure its effectiveness in the market (internal/external)
* Learn from the experiment
* Decide to persevere or pivot (change direction while leveraging momentum)
* New idea development, evolution of MVP

===== Impact mapping
 [TBW]

===== Features vs. components

anchor:2.04.02-features-v-components[]
As your product evolves, you may see an increasing differentiation of concerns, between features and components.

Features are *what* your product *does*. They are what the customers perceive as valuable. “Scope as viewed by the customer” as <<Kennaley2010>> says (p. 169).

Components are *how* your product is *built*, such as database vs. Web components. In other words, they are a form of infrastructure (but infrastructure you may need to build yourself, rather than just spin up in the Cloud).

Feature teams are dedicated to a clearly defined functional scope, while component teams are defined by their technology platform. Component teams may become shared services, which need to be carefully understood and managed (more on this in Section 3).

It may be easy to say that features are more important than components, but this can easily be carried too far. Do you want each feature team choosing its own database? Not recommended. Allowing feature teams to define their own technical direction can result in brittle, fragmented architectures, technical debt, and rework.

Software product management needs to be a careful balance between these two perspectives. Some http://blog.octo.com/en/feature-team-beyond-the-buzzword/[recommend] a ratio of:

* 70-80% Feature teams to

* 20-30% Component teams

We will be revisiting this more systematically in chapter 7.

===== Software and systems engineering

Some of the most contentious discussions related to IT management and Agile come at the intersection of software and systems engineering, especially when large investments are at stake.

Frequent criticisms of Lean Startup and related trends are:

* They are relevant only for non-critical Internet-based products (e.g. Facebook and Netflix)
* Some IT products must fit much tighter specifications and do not have the freedom to "pivot" (e.g. aerospace & defense systems)

===== Parable: The flower and the cog
 [TBW]
