==== Lean, Lean Product Development, and Don Reinertsen

We've had passing mention of Lean already in this book. But what is Lean?

Lean is the name given to a cohesive set of practices generally attributed to https://en.wikipedia.org/wiki/Taiichi_Ohno[Taiichi Ohno] and https://en.wikipedia.org/wiki/Shigeo_Shingo[Shigeo Shingo] at https://en.wikipedia.org/wiki/Toyota[Toyota]. These practices included:

* Respect for people
* Small batch sizes (driving towards "single piece flow")
* Just-in-time production
* Increased cycle time

There are many, many other aspects to Lean.

IMPORTANT: Lean is important. Regardless of your intended career path, it is advisable to read the great Lean classics, including http://www.goodreads.com/book/show/93903.Machine_That_Changed_the_World[The Machine That Changed the World], http://www.goodreads.com/book/show/289467.Lean_Thinking[Lean Thinking], http://www.goodreads.com/book/show/161789.The_Toyota_Way[The Toyota Way], and Ohno's own http://www.goodreads.com/book/show/376237.Toyota_Production_System[Toyota Production System]. http://www.goodreads.com/book/show/6736366-toyota-kata[Toyota Kata] is a more recent work, highly informative regarding Toyota's culture.

One of the challenges however with applying Lean to IT (as noted previously) is that many IT professionals (especially software developers) believe that manufacturing is a "deterministic" field and any lessons from it are inapplicable to developing technical products. "Creating software is like creating art, not being on an assembly line" goes one line of argument.

The root cause of this debate is the distinction between product development and production. It is true that an industrial production line may be repetitive, but the question is: how did the production line come to be? It was created as part of a process of product development. *That* is not a repetitive process; it is a highly variable, creative process.

One dead end that management keeps pursuing is the desire to make research and development (R&D) more "predictable," that is, to reduce the variation and predictably create innovations. This never works well; game-changing innovations are usually complex responses to complex market systems dynamics, including customer psychology, current trends, and many other factors.

In IT, simply developing software for a new problem (or even new software for an old problem) is an R&D problem, not a production line problem. It is iterative, uncertain, and risky of success, just like other forms of product development.

But that does not mean it is completely un-manageable, that its creation is a myterious artistic process. It is just a more variable process, with a higher chance of failure, and a need to incorporate feedback quickly to avoid any risk of open-loop control failure.



asymmetric rewards

pyramid

OODA sidebar
