=== Chapter 8: Project & Resource Management

Project management is traditionally defined as the execution of a given scope of work within constraints of time and budget. As we have seen in our discussions of product management, in implementing truly new IT-based products, estimating time and budget can be difficult because the necessary information is not available. In fact, creating it is the actual work of the "project". Therefore, in the new Agile world, there is some uncertainty as to the role and even need for traditional project management.

However, at a practical level, project managers remain important roles and are employed at both "unicorn" and "horse" companies as overall orchestrators of complex initiatives. Financial planning has not gone away and without project management, financial planning meets difficult challenges. The very concept of having a vision becomes problematic without some ability to plan.

Because of this, this chapter also covers IT financial management at a very introductory level.

==== Introduction to Chapter 8

===== Chapter 8 outline

* Introduction to project management
 - PMBOK etc (also covered in Appendix)
 - Scrum and XP (Scrum introduced in 5, need to figure out correct allocation)
  - Notice that Scrum originated from Sutherland's study of product management, not project management

* Is project management still needed in a product-centric world?
 - yes. Google & FB both use it.

* Project management antipatterns

****
Sidebar: Introducing Scaled Agile Framework (Leffingwell)
****

* The estimation controversy (sidebar?)

* The future of project management

* Resource management (yes, it's a terrible name)
  _get permission for Dilbert cartoon "I am not a resource"_
  - SFIA framework
  - Approaches to time tracking

* Supply and demand.
  - IT talent
  - DSE - alternate view to PBR]
  - 2 dimensions of demand management
  - More to come in portfolio mgmt
  - Last responsible moment
  - Ops theory - process, project, execution, resource & scheduling constraints

  * Introduction to IT financial management


===== Chapter 8 learning objectives
* Identify the basic practices of project management
* Identify the basic concerns of IT resource management
* Identify the basic concerns of IT financial management


When risk
and uncertainty are present with ongoing demand, like in the case of
architectural changes and related high-stake decisions, batching demand
194into a project for governance reasons makes sense. And when new
demand (even fine-grained demand) arrives in a product's Backlog,
determination must occur as to whether itwarrants a new generation of
the product based on changing business conditions or IT technology
evolution. Adecision tree can be leveraged to determine if a product
request should qualify for maintenance, or requires project facilities (*** kennaley sdlc3 195)
