
anchor:financial-mgmt[]

==== IT financial management

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is work in process as of 2016-05-04, expect volatility

 Needs: IT financial management experts also familiar with Beyond Budgeting or Lean Accounting. All 3 of you.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

[quote, Rami  Sirkiä  and  Maarit  Laanti ]
The traditional system provides, at best, a false sense of cost control to any enterprise

Our "from startup to enterprise" thought experiment has always been intended to apply to an individual's journey through a large organization, as well as a genuine case of company growth. However, a company scaling up today would often make different decisions from a company who scaled up 40 years ago. This is especially apparent in the matter of how to finance digital/IT systems development and operations.

One of the major reasons that projects were conceived as large "batches" of work has been the annual budgeting cycle. In this well established practice, companies once a year embark on a detailed planning cycle to forecast revenues and plan how they will be spent. Much emphasis is placed on the accuracy of such forecasts, despite its near-impossibility. (If estimating one large software project is challenging, how much more challenging to estimate an entire enterprise's income and expenditures?)

The annual budget has two primary components: capital expenditures and operating expenditures, commonly called CapEx and OpEx. The rules about what must go where are fairly rigid and determined by accounting standards with some leeway for the organization's preferences.

Software development in general is capitalized, as it is an investment from which the company hopes to benefit from in the future. Operations is typically expensed. Capitalized activities may be accounted for over multiple years (therefore becoming a reasonable candidate for financing and multi-year amortization.) Expensed activities must be accounted for in-year.

Because one can only "go to the well" once a year, extensive planning and negotiation traditionally takes place around the IT project portfolio. Business units and their IT partners debate the priorities for the capital budget, assess resources, and finalize a list of investments. Project managers are identified and tasked with marshaling the needed resources for execution.

At the same time, the IT operations staff is fighting for its budget, which is usually under constant pressure to "do more with less."

IT is often consumed as a "shared service" which requires internal financial transfers. What does this mean?

Here is a traditional example. An IT group purchases a mainframe computer for $1,000,000. This mainframe is made available to various departments who are charged for it. Because the mainframe is a shared resource, it can run multiple workloads simultaneously. For the year, we see the following usage:

* 30% Accounting
* 40% Sales operations
* 30% Supply chain

In the simplest direct allocation model, the departments would pay for the portion of the mainframe that they used. But things always are more complex than that.

* What if the mainframe has excess capacity? Who pays for that?
* What if Sales Operations stops using the mainframe? Do Accounting and Supply Chain have to make up the loss? What if Accounting decides to stop using it because of the price increase? (In public utilities, this is known as a http://www.greentechmedia.com/articles/read/this-is-what-the-utility-death-spiral-looks-like["death spiral."])
* The mainframe requires power, floor space, and cooling. How are these incorporated into the departmental charges?

IMPORTANT: Financial management is a broad and complex topic, and its intersection with IT and digital management is even more complex as well as evolving. This brief section can only cover a few basics. See the recommended readings for further information.

===== Basic concerns
[quote, Terence Quinlan, IT Financial Management Association]
Computers initially were used to automate manual operations and the benefits were relatively easy to forecast. As organizations use computers more for strategic purposes and management information enhancements, the benefits become harder to forecast. In a growing number of companies the individuals most qualified to forecast the most significant costs and benefits are product managers, financial specialists, marketing specialists, and not the I/S technical specialists . . .

In IT/digital service organizations, there are three basic sources of cost: "cells, atoms, and bits." That is:

* People (i.e. their time)
* Hardware
* Software

However, these are "direct" costs - costs that for example a product or project manager can see in their full amount.

Another class of cost is "indirect." The IT service might be charged $300 per square foot for data center space. This provides access to rackspace, power, cooling, security, and so forth.  This charge represents the bills the Facilities organization in turn receives from power companies, mechanicals vendors, security services, and so forth - not to mention the mortgage!

Finally, the service may depend on other services. Perhaps instead of a dedicated database server, the service subscribes to a database *service* that gives them a high-performance relational database, but where they do not pay directly for the hardware, software, and support services the database is based on.

The execution model for digital/IT acquisition adds further complexity. Traditionally, project management has been the major funding vehicle for capital investments, distinct from operational expense. However, with the rise of Cloud computing and product-centric management, companies are moving away from traditional capital projects. New products are created with greater agility, in response to market need, and without the large capital investments of the past in physical hardware.

But this does not mean that traditional accounting distinctions between capex and opex go away. Software development may still be capitalized, as may software licenses.

All of these factors contribute to significant challenges in planning and accounting for IT from a financial management perspective.

Historically, *cost accounting* has been the basis for much IT financial management (see e.g. ITIL Service Strategy, <<TSO2011a>>, p.202).

NOTE: *Cost accounting* is defined as "the techniques for determining the costs of products, processes, projects, etc. in order to report the correct amounts on the financial statements, and assisting management in making decisions and in the planning and control of an organization . . .For example, cost accounting is used to compute the unit cost of a manufacturer's products in order to report the cost of inventory on its balance sheet and the cost of goods sold on its income statement. This is achieved with techniques such as the allocation of manufacturing overhead costs and through the use of process costing, operations costing, and job-order costing systems. <<Accounting2016>>



However, cost accounting in Lean and Agile organizations is often controversial. Lean pioneer Taiichi Ohno of Toyota was legendary for stating "It was not enough to chase out the cost accountants from
the plants, the problem was to chase cost accounting from my people's minds" <<Huntzinger2007>>, p. 24.

The trend in Lean Accounting has been to simplify complex cost accounting

The "ideal" for a manufacturing company is to have only two types of transactions within the production processes; the receipt of raw materials and the shipment of finished product. https://en.wikipedia.org/wiki/Lean_accounting

===== Agile challenges (Lean Accounting, Beyond Budgeting)

****
IT organizations typically adhere to annual budgeting and planning cycles—which can involve painful rebalancing exercises across an entire portfolio of technology initiatives, as well as a sizable amount of rework and waste. This approach is anathema to companies that are seeking to deploy agile at scale. Some businesses in our research base are taking a different approach. Overall budgeting is still done yearly, but road maps and plans are revisited quarterly or monthly, and projects are reprioritized continually.

A large European insurance provider restructured its budgeting processes so that each product domain is assigned a share of the annual budget, to be utilized by chief product owners. (Part of the budget is also reserved for requisite maintenance costs.) Budget responsibilities have been divided into three categories: a development council consisting of business and IT managers meets monthly to make go/no-go decisions on initiatives. Chief product owners are charged with the tactical allocation of funds—making quick decisions in the case of a new business opportunity, for instance—and they meet continually to rebalance allocations.

Meanwhile, product owners are responsible for ensuring execution of software development tasks within 40-hour work windows and for managing maintenance tasks and backlogs; these, too, are reviewed on a rolling basis. As a result of this shift in approach, the company has increased its budgeting flexibility and significantly improved market response times.

A handful of companies are even exploring a venture-capital-style budgeting model. Initial funding is provided for minimally viable products (MVPs), which can be released quickly, refined according to customer feedback, and relaunched in the marketplace—the hallmarks of agile development. And subsequent funding is based on how those MVPs perform in the market. Under this model, companies can reduce the risk that a project will fail, since MVPs are continually monitored and development tasks reprioritized. Typically there is less waste and more transparency among portfolio and product managers, and it becomes easier for the company to scrap low-potential projects early.  <<Comella2016>>
****

****
Firstly, traditional cost center accounting ex ects a long horizon with detailed cost estimates that must be frequently u dated. Sim ly  ut, agile SW develo ment avoids this detailed and long horizon  lanning. Secondly, traditional cost accounting values  lanning accuracy and executes variance analysis against the original estimate. Agile develo ment instead allows for uncertainty: the final content delivery and total cost may be im acted by the em irical feedback received. Thirdly, traditional budgeting draws attention to budget overruns. In agile develo ment, if the initial feedback  roves to be  ositive we want to allow – and even encourage – further investments. In larger enter rises the division of investment can be controlled via the hierarchy of backlogs – the level of investment is dictated by the changing backlog  riorities, which means the teams allocate tasks flexibly. Fourthly, traditional  roject cost accounting requires a re-°©‐ a  roval for any delays which increase the  roject budget. Rigid a  roval limits  ose an unnecessary control, and thus, in agile develo ment, delays that would traditionally be caused by the budgetary a  roval  rocess means teams can now take their order of develo ment flexibly from the  rioritized backlogs.

...The rigid organizational structure, narrow competence profiles and detailed level of projects with dedicated resources prevented prompt and flexible resource reallocation. The idea of allowing more flexible organization structure with empowered teams was born and supported by our R&D management team roughly at the same time when the idea of more flexible investment planning and control was born.

...While agile development has largely been adopted around the globe, traditional management methods need to be changed in response.

<<Sirkia2013>>
****
