
anchor:financial-mgmt[]

==== IT financial management

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is work in process as of 2016-05-04, expect volatility

 Needs: IT financial management experts also familiar with Beyond Budgeting or Lean Accounting. All 3 of you.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

[quote, Rami  Sirkiä  and  Maarit  Laanti ]
The traditional system provides, at best, a false sense of cost control to any enterprise . . .

Our "from startup to enterprise" thought experiment has always been intended to apply to an individual's journey through a large organization, as well as a genuine case of company growth. However, a company scaling up today would often make different decisions from a company who scaled up 40 years ago. This is especially apparent in the matter of how to finance digital/IT systems development and operations.

IMPORTANT: Financial management is a broad and complex topic, and its intersection with IT and digital management is even more complex as well as evolving. This brief section can only cover a few basics. However, it is important for you to have an understanding of the intersection of Agile and Lean IT with finance, as your organization's financial management approach can determine the effectiveness of your digital strategy.  See the recommended readings for further information.

===== Basic concerns
[quote, Terence Quinlan, IT Financial Management Association]
Computers initially were used to automate manual operations and the benefits were relatively easy to forecast. As organizations use computers more for strategic purposes and management information enhancements, the benefits become harder to forecast. In a growing number of companies the individuals most qualified to forecast the most significant costs and benefits are product managers, financial specialists, marketing specialists, and not the I/S technical specialists . . .

Financial health is an essential dimension of business health. And digital technology has been one of the fastest-growing budget items in modern enterprises. Its relationship to enterprise financial management has been a concern since the first computers were acquired for business purposes.

The objectives of IT finance include:

* Providing a framework for tracking and accounting for digital income and expenses
* Supporting financial analysis of digital strategies (business models and operating models, including sourcing)
* Support the digital and IT-related aspects of the corporate budgetary and reporting processes, including internal and external policy compliance
* Supporting (where appropriate) internal cost recovery from business units consuming digital services
* Support accurate and transparent comparison of IT financial performance to peers and market offerings (benchmarking)

One of the major reasons that projects were conceived as large "batches" of work has been the annual budgeting cycle. In this well established practice, companies once a year embark on a detailed planning cycle to forecast revenues and plan how they will be spent. Much emphasis is placed on the accuracy of such forecasts, despite its near-impossibility. (If estimating one large software project is challenging, how much more challenging to estimate an entire enterprise's income and expenditures?)

The annual budget has two primary components: capital expenditures and operating expenditures, commonly called CapEx and OpEx. The rules about what must go where are fairly rigid and determined by accounting standards with some leeway for the organization's preferences.

Software development in general is capitalized, as it is an investment from which the company hopes to benefit from in the future. Operations is typically expensed. Capitalized activities may be accounted for over multiple years (therefore becoming a reasonable candidate for financing and multi-year amortization.) Expensed activities must be accounted for in-year.

Because one can only "go to the well" once a year, extensive planning and negotiation traditionally takes place around the IT project portfolio. Business units and their IT partners debate the priorities for the capital budget, assess resources, and finalize a list of investments. Project managers are identified and tasked with marshaling the needed resources for execution.

At the same time, the IT operations staff is fighting for its budget, which is usually under constant pressure to "do more with less."

IT is often consumed as a "shared service" which requires internal financial transfers. What does this mean?

Here is a traditional example. An IT group purchases a mainframe computer for $1,000,000. This mainframe is made available to various departments who are charged for it. Because the mainframe is a shared resource, it can run multiple workloads simultaneously. For the year, we see the following usage:

* 30% Accounting
* 40% Sales operations
* 30% Supply chain

In the simplest direct allocation model, the departments would pay for the portion of the mainframe that they used. But things always are more complex than that.

* What if the mainframe has excess capacity? Who pays for that?
* What if Sales Operations stops using the mainframe? Do Accounting and Supply Chain have to make up the loss? What if Accounting decides to stop using it because of the price increase? (In public utilities, this is known as a http://www.greentechmedia.com/articles/read/this-is-what-the-utility-death-spiral-looks-like["death spiral."])
* The mainframe requires power, floor space, and cooling. How are these incorporated into the departmental charges?

Two major themes have characterized IT financial management for the past decades: cost accounting and project management.

===== Cost Accounting

Historically, *cost accounting* has been the basis for much IT financial management (see e.g. ITIL Service Strategy, <<TSO2011a>>, p.202; <<Quinlan2003>>). Such approaches traditionally seek _full absorption_ of unit costs; that is, each "unit" of inventory ideally represents the total cost of all its inputs: materials, labor, and overhead such as machinery and buildings.

NOTE: *Cost accounting* is defined as "the techniques for determining the costs of products, processes, projects, etc. in order to report the correct amounts on the financial statements, and assisting management in making decisions and in the planning and control of an organization  . . . For example, cost accounting is used to compute the unit cost of a manufacturer's products in order to report the cost of inventory on its balance sheet and the cost of goods sold on its income statement. This is achieved with techniques such as the allocation of manufacturing overhead costs and through the use of process costing, operations costing, and job-order costing systems. <<Accounting2016>>

In IT/digital service organizations, there are three basic sources of cost: "cells, atoms, and bits." That is:

* People (i.e. their time)
* Hardware
* Software

However, these are "direct" costs - costs that for example a product or project manager can see in their full amount.

Another class of cost is "indirect." The IT service might be charged $300 per square foot for data center space. This provides access to rackspace, power, cooling, security, and so forth.  This charge represents the bills the Facilities organization in turn receives from power companies, mechanicals vendors, security services, and so forth - not to mention the mortgage!

Finally, the service may depend on other services. Perhaps instead of a dedicated database server, the service subscribes to a database *service* that gives them a high-performance relational database, but where they do not pay directly for the hardware, software, and support services the database is based on. Just to make things more complicated, the services might be external (public Cloud) or internal (private Cloud or other offerings).

Those are the major classes of cost. But how do we understand the "unit of inventory" in an IT services context? A variety of concepts can be used, depending on the service in question:

* Transactions
* Users
* Network ports
* Storage (e.g. gigabytes of disk)

In internal IT organizations (see xref:consumer-customer-sponsor["Defining consumer, customer, and sponsor"]) this cost accounting is then used to transfer funds from the budgets of consuming organizations to the IT budget. Sometimes this is done via simple allocations (Marketing pays 30%, Sales pays 25%, etc) and sometimes this is done through more sophisticated approaches, such as defining unit costs for services.

For example, the fully absorbed unit cost for a customer account transaction might be determined to be $0.25; this ideally represents the total cost of the hardware, software, and staff divided by the expected transactions. Establishing the models for such costs, and then tracking them, can be a complex undertaking, requiring correspondingly complex systems.

IT managers have known for years that overly detailed cost accounting approaches can result in consuming large fractions of IT resources. As AT&T financial manager John McAdam noted:

"Utilizing an excessive amount of resources to capture data takes away resources that could be used more productively to meet other customer needs. Internal processing for IT is typically 30-40% of the workload. Excessive data capturing only adds to this overhead cost." <<McAdam2003>>

There is also the problem that unit costing of this nature creates false expectations. Establishing an internal service pricing scheme implies that if the utilization of the service declines, so should the related billings. But if

. the hardware, software, and staff costs are already sunk, or relatively inflexible and
. the IT organization is seeking to fully recover costs

the per-transaction cost will simply have to increase if the number of transactions goes down.

===== Project funding

The execution model for digital/IT acquisition adds further complexity. Traditionally, project management has been the major funding vehicle for capital investments, distinct from operational expense. But with the rise of Cloud computing and product-centric management, companies are moving away from traditional capital projects. New products are created with greater agility, in response to market need, and without the large capital investments of the past in physical hardware.

This does not mean that traditional accounting distinctions between capex and opex go away. Software development may still be capitalized, as may software licenses.

All of these factors contribute to significant challenges in planning and accounting for IT from a financial management perspective.


"it is an absolutely necessary element of accurate representation of the facts of production that some provisions be made for keeping the cost of wasted time and resources separate from normal costs." <<Huntzinger2007>> re the death spiral problem

===== New approaches to IT finance
[quote, Orest Fiume and Jean Cunningham, as quoted by James Huntzinger]
What accounting should do is produce an unadulterated mirror of the business — an uncompromisable truth on which everyone can rely. ... Only an informed team, affer all, is truly capable of making intelligent decisions.

What do critics of cost accounting and large batch project funding suggest? A variety of themes and approaches have emerged:

* Value stream orientation
* Internal "venture" funding
* Lean Product Development
* Lean Accounting & Beyond Budgeting
* Internal market economics
* Service brokerage


We will discuss the value stream orientation, internal "venture" funding and briefly recap Reinertsen's xref:cost-of-delay[Cost of Delay] (first introduced in Chapter 4) in terms of the investment cycle, Lean alternatives to services cost accounting, and finally the concept of internal market economics.

====== Value stream orientation



====== The investment cycle

Beyond Budgeting

Cost of Delay

====== Lean accounting

[quote, Taiichi Ohno]
It was not enough to chase out the cost accountants from the plants, the problem was to chase cost accounting from my people's minds.

There are several often-cited motivations for cost accounting (<<Huntzinger2007>> p 13):

* Inventory valuation
* Informing pricing strategy
* Management of production costs

Inventory valuation of course is not applicable for intangible services. IT service costing has long presented additional challenges to traditional cost accounting. As IT Financial Management Association president Terry Quinlan notes, "Many factors have contributed to the difficulty of planning EDP expenditures at both application and overall levels. A major factor is the difficulty of measuring fixed and variable cost." <<Quinlan2003>>, p. 6.

the cost-management system in a lean environment must be more reflective of the
physical operation. It must not be confined to monetary measures but must also
include nonfinancial measures, such as quality and throughput times.^<<Huntzinger2007>>

However, this begs the broader question: should cost accounting be the primary accounting technique used at all? Cost accounting in Lean and Agile organizations is often controversial. Lean pioneer Taiichi Ohno of Toyota thought it was a flawed approach. Huntzinger <<Huntzinger2007>> identifies a variety of issues:

* Complexity
* Un-maintainability
* Supplies information "too late" (i.e., does not support fast feedback)

Shingo Prize winner Steve Bell observes:

****
It is usually impossible to tie  . . . abstract cost allocations and the resulting variances back to the originating activities and the value they may or may not produce; thus, they can't help you improve. But they can waste your time and distract you from the activities that produce the desired outcomes . . . <<Bell2013>>, p 110.
****

Both questionable... Pricing is subject to the market...

The trend in Lean Accounting has been to simplify ....

The "ideal" for a manufacturing company is to have only two types of transactions within the production processes; the receipt of raw materials and the shipment of finished product. https://en.wikipedia.org/wiki/Lean_accounting

====== Service brokerage
Can overcome the excess capacity problem by sourcing



====== Internal market economics
collecting costs into traditional financial accounting categories, like labor, material, overhead, selling, distribution, and administrative, will conceal the underlying cost structure of products . . .

The alternative to traditional methods, which Church developed and promoted and Dr. Johnson and Kaplan allude to, is the creation of an environment that moves indirect costs and allocation into direct costs. This change is achieved by implementing physical changes or one-piece flow in the form of cellular manufacturing of value streams. Managers of the manufacturing enterprise must understand what changes must be made and where they must be made in order to be successful.

 <<Huntzinger2007>>

====== quotes/notes

 cost information is formed and calculated by a direct reflection of the physical flow of products within the value stream. <<Huntzinger2007>> p.6-7 - [how to interpret for services]

 the accounting system must be a subservient system to the production system <<Huntzinger2007>> p.3.

 A machine's value is not determined by its years of service or its age. It is determined by the earning power it still retains. <<Ohno1988>>, p.64.

 each good, service, and piece of information must have a simple, prespecified, self-diagnostic flow-path over which it will travel as it takes form. (Spear as in Huntzinger, waiting on source material)

 every activity along the value stream or flow-path is predetermined, meaning predesigned and prelearned. [OK this really doesn't work for dev, b/c systems development IS a learning - but does work for transactional ops]

This DIP inventory is actually more important than inventory in the
factory, because it is much larger and more expensive to hold. Manufac
turing plants turn their inventory with incredibly fast cycle times. Mod
ern plants can turn their inventory more than fifty times a year. In
contrast, it is the rare development process that achieves more than one
turn per year. Thus, DIP can be a much larger number than WIP in most
companies. As the data in the Figure 1.1 show, DIP can easily be ten
times bigger than WIP in many situations.
Furthermore, holding costs are much higher for DIP than for WIP. A
traditional rule of thumb for the cost of holding WIP is about 25 percent
of the inventory value per year. This takes into account the cost of stor
age, the risk of obsolescence, the cost of capital employed, and so on.
The holding costs for DIP are much higher because the risk of obsoles
cence is high. In certain categories, a product that arrives to market two
years late will have zero value. Most manufacturing inventory does not
drop to zero value nearly as quickly.
You would think that the high levels of DIP and the high cost of hold
ing DIP wouldbe incentives for managementto measure and manage it.
Sadly, it is ignored, due to a critical weakness of our accounting systems.
The invisibility of DIP is actually a cruel trick played on us by Gener
ally Accepted Accounting Principles (GAAP). Long ago, accountants
agreed that R&D expenses should be recognized at the time the money
is spent. They maintained that the value of a partially completed design
could not be assessed with enough accuracy to treat it as a financial
asset. They asserted that companies would inflate their balance sheets
and overstate their profits by claiming that money spent on R&D was
the same as deposits in a bank.
These arguments are sound, but the unfortunate consequence of such
sound accounting practices is that DIP is invisible on our financial state
ments. Neither shareholders nor managers have any clue whether they
are managing this resource well. Because we never show it on our bal
ance sheet, we do not think of DIP as an asset to be managed, and we do
not manage it. <<Reinertsen1997>> p13




====== Internal market economics
Dean Meyer critiques/approach

Fractal / lean

****
IT organizations typically adhere to annual budgeting and planning cycles—which can involve painful rebalancing exercises across an entire portfolio of technology initiatives, as well as a sizable amount of rework and waste. This approach is anathema to companies that are seeking to deploy agile at scale. Some businesses in our research base are taking a different approach. Overall budgeting is still done yearly, but road maps and plans are revisited quarterly or monthly, and projects are reprioritized continually.

A large European insurance provider restructured its budgeting processes so that each product domain is assigned a share of the annual budget, to be utilized by chief product owners. (Part of the budget is also reserved for requisite maintenance costs.) Budget responsibilities have been divided into three categories: a development council consisting of business and IT managers meets monthly to make go/no-go decisions on initiatives. Chief product owners are charged with the tactical allocation of funds—making quick decisions in the case of a new business opportunity, for instance—and they meet continually to rebalance allocations.

Meanwhile, product owners are responsible for ensuring execution of software development tasks within 40-hour work windows and for managing maintenance tasks and backlogs; these, too, are reviewed on a rolling basis. As a result of this shift in approach, the company has increased its budgeting flexibility and significantly improved market response times.

A handful of companies are even exploring a venture-capital-style budgeting model. Initial funding is provided for minimally viable products (MVPs), which can be released quickly, refined according to customer feedback, and relaunched in the marketplace—the hallmarks of agile development. And subsequent funding is based on how those MVPs perform in the market. Under this model, companies can reduce the risk that a project will fail, since MVPs are continually monitored and development tasks reprioritized. Typically there is less waste and more transparency among portfolio and product managers, and it becomes easier for the company to scrap low-potential projects early.  <<Comella2016>>
****

****
Firstly, traditional cost center accounting ex ects a long horizon with detailed cost estimates that must be frequently u dated. Sim ly  ut, agile SW develo ment avoids this detailed and long horizon  lanning. Secondly, traditional cost accounting values  lanning accuracy and executes variance analysis against the original estimate. Agile develo ment instead allows for uncertainty: the final content delivery and total cost may be im acted by the em irical feedback received. Thirdly, traditional budgeting draws attention to budget overruns. In agile develo ment, if the initial feedback  roves to be  ositive we want to allow – and even encourage – further investments. In larger enter rises the division of investment can be controlled via the hierarchy of backlogs – the level of investment is dictated by the changing backlog  riorities, which means the teams allocate tasks flexibly. Fourthly, traditional  roject cost accounting requires a re-°©‐ a  roval for any delays which increase the  roject budget. Rigid a  roval limits  ose an unnecessary control, and thus, in agile develo ment, delays that would traditionally be caused by the budgetary a  roval  rocess means teams can now take their order of develo ment flexibly from the  rioritized backlogs.

...The rigid organizational structure, narrow competence profiles and detailed level of projects with dedicated resources prevented prompt and flexible resource reallocation. The idea of allowing more flexible organization structure with empowered teams was born and supported by our R&D management team roughly at the same time when the idea of more flexible investment planning and control was born.

...While agile development has largely been adopted around the globe, traditional management methods need to be changed in response.

<<Sirkia2013>>
****
