==== Conclusion


fundamental theme - what can we know... emergence vs planning ... network vs chain ... finding partial ordering, falsifying hypotheses...

If we "get rid of the PMO" there still is the need to charter new investments. What is their value proposition, business model... there is always a portfolio and some form of success criteria and there will ALWAYS be issues of resources and dependencies


===== Discussion questions
* Imagine yourself in an organization that recognized product management and work management, but had no concept of project management. Describe a scenario where project management would be a reasoanble technique to introduce.

* What experience do you or your team members have with project management? How effective did you find it?

* Do microservices/continuous delivery/devops render traditional PM obsolete?

===== Research & practice
* Compare Microsoft Project with one of the following. What are the pros and cons?
** Rally
** Jira
** VersionOne
** Asana



===== Further reading

Project management is a deep and wide field, at its most mature showing the influence of operations theory and research. This section is intended to give you a brief overview of its foundational elements and reach. For a more in depth treatment, see <<PMI2013>> and <<Richardson2010>>. For Agile,  Lean, and Theory of Constraints aspects, see <<Cobb2015>>, <<Goldratt1997>>, and (once again) <<Reinertsen2009>> (especially the discussion of Weighted Shortest Job First).

*Books*

* Charles G. Cobb, http://www.goodreads.com/book/show/24844947-the-project-manager-s-guide-to-mastering-agile[The Project MANAGER'S GUIDE TO MASTERING AGILE: Principles and Practices for an Adaptive Approach]

* Project Management Institute, http://www.goodreads.com/book/show/16192710-a-guide-to-the-project-management-body-of-knowledge-pmbok-guide---5th[A Guide to the Project Management Body of Knowledge (Pmbok Guide) - 5th Edition]

* Gary L. Richardson,  http://www.goodreads.com/book/show/8085475-project-management-theory-and-practice[Project Management Theory And Practice]

* Brooks, Mythical Man-Month

*Articles*

* http://www.slideshare.net/garydrumm/project-management-101-primer[Project Management 101]

* https://www.mountaingoatsoftware.com/articles/the-need-for-agile-project-management[The Need for Agile Project Management]

* https://www.thoughtworks.com/insights/blog/project-vs-product[Project vs. Product]

* https://www.thoughtworks.com/insights/blog/scaling-agile-problems-and-solutions[Scaling Agile: Problems and Solutions]

*Resources*


*Videos*

*Professional*
