
anchor:resource-mgmt[]

==== IT resource management
 (yes, it's a terrible name)
  _get permission for Dilbert cartoon "I am not a resource"_ http://dilbert.com/strip/1995-09-22

===== Basic concerns


===== Hiring
[quote, Sean Landis, Agile Hiring]
hiring is one of the most important things a software organization does. Every good hire accelerates your organization; every poor hire is a drag on your organization.

Your organization has been hiring people for some time now, but you have reached the point where a more formal and explicit understanding of how you do this is essential.

We covered culture in Chapter 7;

* Mythical man-month
* Generalizing specialists
* Pairing, swarming, mobbing http://www.jrothman.com/mpd/project-management/2014/07/how-pairing-swarming-work-why-they-will-improve-your-products/

10x controversy

===== Resource allocation
process management in chapter 9
multi-project fractional allocation
resources impacted by operational processes
ad-hoc requests
sum total of demand - overburden
Phoenix Project examination - all just work

the various time tracking approaches

* roll up FTE to product & don't
* project systems
* HR systems
* ticketing systems (process centric)
* home built systems

project IDs

===== Accountability and performance

broken older models - linear 1-5 ranking once a year
360 degree
etc.


===== SFIA framework

good blogs:

Johanna Rothmann
