
anchor:resource-mgmt[]
anchor:_it_resource_management[]

==== IT human resource management

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is 1st draft as of 2016-05-04.

 Needs: As you review this, please keep in mind that it is a secondary section to the overall chapter "Project and Resource Management." Another case study would be OK and I think that the end doesn't quite take it home yet. Of course anything I have completely missed would be great feedback!

 Resource management is a terrible name. We will use it anyways.
 Todo: get permission for Dilbert cartoon "We're human beings not resources" http://dilbert.com/strip/1995-09-22

* Raise an link:https://github.com/dm-academy/aitm/issues[issue, window="_blank"] to comment
* link:https://raw.githubusercontent.com/dm-academy/aitm/master/book/3-section-III/3.08-chap-8/3.08.05-resource-mgmt.adoc[Github source, window="_blank"]
* link:https://github.com/dm-academy/aitm/blob/master/collaborator-instructions.adoc[Collaborator instructions, window="_blank"]
****

endif::collaborator-draft[]



===== Basic concerns
Human Resource management can also be termed "people management." It is distinct from supply chain and technology management, being concerned with the identification and recruitment, onboarding, ongoing management for value, and eventual exit of individuals from an organization.

This brief section covers the topic as it relates to digital management, incorporating recent cases and perspectives.

===== Hiring
[quote, Sean Landis, Agile Hiring]
hiring is one of the most important things a software organization does. Every good hire accelerates your organization; every poor hire is a drag on your organization.

Here is a typical hiring process:

* Solicit candidates, through various channels such as job boards and recruiters
* Review resumes and narrow candidate pool down for phone interviews
* Conduct phone interviews and narrow candidate pool down for in person interviews
* Conduct in person interviews, identify candidates for offers
* Make offer, negotiate to acceptance
* Hire and onboard

Your organization has been hiring people for some time now. It's always been one of your most important decisions, but you have reached the point where a more formal and explicit understanding of how you do this is essential.

First, why do you hire new staff? How and when do you perceive a need? It is well established that increasing the size of a team can slow it down. Legendary software engineer Fred Brooks, in his work _The Mythical Man Month_, identified the pattern that "adding more people to a late project makes it later" <<Brooks1995>>.

Are you adding people because of a perceived need for specialist skills? While this will always be a reason for new hires, many argue in favor of "T-shaped" people - people who are deep in one skill, and broad in others. Hiring new staff has an impact on culture - is it better to train from within, or source externally?

Second, how are you hiring staff? In a traditional, functionally specialized model, someone in a Human Resources organization acts as an intermediary between the hiring manager, and the job applicant (sometimes with a recruiter also in the mix between the company and the applicant). Detailed job descriptions are developed, and applicants not explicitly matching the selection criteria (e.g. in their resume) are not invited for an interview.

Such practices do not necessarily result in good outcomes. Applicants routinely tailor resumes to the job description. In some cases they have been known to copy the job description into invisible sections of their resume, so that they are guaranteed a "match" if automated resume-scanning software is used.

A compelling case study of the limitations of traditional HR-driven hiring is discussed by Robert Sutton and Huggy Rao in _Scaling up Excellence : Getting to More without Settling for Less_<<Sutton2014>>. The authors describe the company Lotus Software, one of the pioneers of early desktop computing.

====
With [company founder] Kapor’s permission, [head of organizational development] Klein pulled together the résumés of the first forty Lotus employees...[and] submitted all forty résumés to the Lotus human resources department. Not one of the forty applicants, including Kapor, was invited for a job interview. The founders had built a world that rejected people like them.
====

Sean Landis, author of _Agile Hiring_ <<Landis2011>>, believes that

"accepted hiring wisdom is not very effective when applied to software professionals." He further states that:

* very few companies hire well.
* individuals with deep domain knowledge are in the best position to perform great hiring.
* companies often focus on the wrong candidates.
* It is important to track metrics on the cost and effectiveness of hiring practices

In short, hiring is one of the most important decisions the digital enterprise makes, and it cannot be reduced to a simple process to be executed mechanically.
Requiring senior technical talent to interview candidates may result in improved hiring decisions. However, such requirements add to the overall demand on these individuals.

===== Allocation and tracking people's time

When a new hire enters your organization, they enter a complex system that will structure and direct their daily activities through a myriad of means. The various means that direct their action include:

* Team assignment (e.g. to an ongoing product)
* Project assignment
* Process responsibilities

Notice again the appearance of the xref:2.04.01-process-project-product["3 Ps."]

Product, project, and process become challenging when they are all allowed to generate demand on individuals independently of each other. In the worst case scenario, the *same* individual winds up with:

* Collaborative team responsibilities
* "Fractional" allocation to one or more projects
* Ticketed process responsibilities

NOTE: Fractional allocation is the practice of funding individuals through assigning them at some % to a project. For example, a server engineer might be allocated 25% time to a project for 6 months to define its infrastructure architecture, while being assigned 30% to another project to refresh obsolete infrastructure.

When demand is un-coordinated, these multiple channels can result in multi-tasking and dramatic overburden, and in the worst case the individual becomes the constraint to enterprise value. Project managers expect deliverables on time, and have no visibility to operational concerns (e.g. outages) that may affect the ability of staff to deliver. Ad-hoc requests "smaller than a project, bigger than a ticket" further complicate matters.

The _Phoenix Project_ presents an effective and realistic dramatization of the resulting challenges. Work is entering the system through multiple channels and the overburden on key individuals (such as Brent, the lead systems engineer) has reached crisis proportions. Through a variety of mechanisms, they take control of the demand channels and greatly improve the organization's success. One of the most important lessons is well articulated by Erik, the mentor:

****
“Your job as VP of IT Operations is to ensure the fast, predictable, and uninterrupted flow of planned work that delivers value to the business while minimizing the impact and disruption of unplanned work, so you can provide stable, predictable, and secure IT service...You must figure out how to control the release of work into IT Operations and, more importantly, ensure that your most constrained resources are doing only the work that serves the goal of the entire system, not just one silo. <<Kim2013>>, p.91
****

In order to understand the work, measuring the consumption of people's time is important. There are various time tracking approaches:

* Simple allocation of staff payroll to product or organizational line
* Project management systems (sometimes these are used for weekly time tracking, even for staff that are not assigned to projects - in such cases, placeholder operational projects are created)
* Human Resource Management systems
* Ticketing/workflow systems - advanced systems, such as those found in the Professional Services Automation sector, track time when tickets are in an "open" status.
* Home built systems

There is little industry consensus on best practices here. There are reasonable concerns about the burden of time tracking on employees, and poor data quality resulting from employees attempting to "code" activities when summarizing their time on a weekly or bi-weekly basis.

 Need reviewer input

===== Accountability and performance
[quote, Sriram Narayam, Agile IT Organization Design]
Accountability helps people use their autonomy judiciously.

Regardless of whether the company is a modern digital enterprise or more traditional in its approach, the commitment, performance, and results of employees is a critical concern. The traditional approach to managing this has been an annual review cycle, resulting in a performance ranking from 1-5:

1. Did not meet expectations
2. Partially met expectations
3. Met expectations
4. Exceeded expectation
5. Significantly exceeded expectations

This annual rating determines the employee's compensation and career prospects in the organization. Some companies (notably GE and Microsoft) have attempted "stack rankings" in which the "bottom" performers must be terminated. High profile practitioners however are moving away from this practice <<Brustein2013>>, <<Olson2013>>.

The traditional annual review is a large "batch" of xref:2.00.01-feedback[feedback] to the employee, and therefore ineffective in terms of systems theory, not much better than an xref:2.00.1-open-loop[open-loop] approach. Because of the weaknesses of such slow feedback (not to mention the large annual costs, expensive infrastructure, and opportunity costs of the time spent), companies are experimenting with other approaches.

Deloitte Consulting, as reported in the Harvard Business Review <<Buckingham2015>>, realized that its annual performance review process was consuming two million hours of time annually, and yet was not delivering the needed value. In particular, ratings were suffering from the measurable flaw that they tended to reveal more about the person *doing* the rating, than the person being rated!

They started by redefining the goals of the performance management system: to accurately identify and reward performance, and fuel its further improvements.

A new approach with greater statistical validity was implemented, based on four key questions:

* Given what I know of this person’s
performance, and if it were my money, I
would award this person the highest possible
compensation increase and bonus
* Given what I know of this person’s
performance, I would always want him or her
on my team
* This person is at risk for low performance
* This person is ready for promotion today

In terms of the frequency of performance check-ins, they note:

****
Research into the practices of the best team leaders reveals that they conduct regular check-ins with each team member about near term work . . . to set expectations for the upcoming week, review priorities, comment on recent work, and provide course correction, coaching, or important new information . . .

\. . . If a leader checks in less often than once a week, the team member’s priorities may become vague . . . the conversation will shift from coaching for near term  work to giving feedback about past performance.

\. . . If you want people to talk about how to do their best work in the near future, they need to talk often. And so far we have found in our testing a direct and measurable correlation between the frequency of these conversations and the engagement of team members . . .
****

Sutton and Rao, in _Scaling up Excellence_, discuss the similar case of Adobe. At Adobe, "annual reviews required 80,000 hours of time from the 2,000 managers at Adobe each year, the equivalent of 40 full-time employees. After all that effort, internal surveys revealed that employees felt less inspired and motivated afterwards— and turnover increased."

Because of such costs and poor results, Adobe scrapped the entire performance management system in favor of a "check-in" approach. In this approach, managers are expected to have regular conversations about performance with employees, and are given much more say in salaries and merit increases. The managers themselves are evaluated through random "pulse surveys" that measure how well each manager "sets expectations, gives and receives feedback, and helps people with their growth and development." <<Sutton2014>>, p. 113.

Whether incentives (e.g. pay raises) should be awarded individually or on a team basis is an ongoing topic of discussion in the industry. Results often derive from team performance, and the contributions of any one individual can be difficult to identify. Because of this, Scrum pioneer Ken Schwaber argues that "The majority of the enterprise's bonus and incentive funds need to be allocated based on the team's performance rather than the individual's performance." <<Schwaber2007>>, p.6.

However, this runs into another problem: that of the "free-rider." What do we do about team members who do not pull their weight? Even in self-organizing teams, confronting someone about their behavior is not something people do willingly, or well.

Ideally, teams will self-police, but this becomes less effective with scale. In one case study in the Harvard Business Review, Continental Airlines found that the free rider problem was less of a concern when metrics were clearly correlated with team activity. In their case, the efforts and cooperation of gate teams had significant influence on On-Time Arrival and Departure metrics, which could then be used as the basis for incentives <<Knez2002>>.

Ultimately, both individuals and teams need coaching and direction. Team-level management and incentives must still be supplemented with some feedback loops centering on the individual. Perhaps this feedback is not compensation-based, but the organization must still identify individuals with leadership potential and deal with free riders and toxic individuals.

Observed behaviors are a useful focus. Sean Landis describes the difference between behaviors and skills thus:

****
Two things make good leaders: behaviors and skills. If you focus on behaviors in your hiring of developers, they will be predisposed for leadership success. The hired candidate may walk in the door with the skills necessary to lead or not. If not, skills are easy to acquire through training and mentoring. People can acquire or modify behaviors, but it is much harder than skill development. Hire for behaviors and train the leadership skills. <<Landis2011>>
****

He further provides many examples of behaviors, such as:

* Adaptable
* Accountable
* Initiative Taker
* Optimistic
* Relational

In conclusion - Many executives and military leaders have identified the central importance of hiring decisions over the years. In large, complex organizations, choosing the right people is the most powerful lever a leader has to drive organizational performance. As we discussed in Chapter 7 and in this chapter, the organizational context these new hires find themselves in will profoundly affect them and the results of their efforts.
