anchor:sourcing[]

==== IT sourcing and contract management
*IT sourcing* is the set of concerns related to identifying suppliers (sources) of the necessary inputs to deliver digital value. *Contract management* is a critical, subsidiary concern, where digital value intersects with law.

The basic classes of inputs include:

* People (with certain skills and knowledge)
* Hardware
* Software
* Services (which themselves are composed of people, hardware, and/or software)

Practically speaking, these inputs are handled by two different functions:

* People (in particular, full time employees) are handled by a Human Resources function.
* Hardware, software, and services are handled by a Procurement function. Other terms associated with this are Vendor Management, Contract Management, and Supplier Management. We will not attempt to clarify or rationalize these areas in this section.

We will defer the question of people and their skills and knowledge to the next section.

===== Basic concerns

****
*Case study: Choosing a telecommunications provider*

When Company X was a startup, its telecommunications needs were limited, as were its options. The founder had one choice for Internet access, the local cable company. Even when the company moved to a larger space, as a single team startup, its options were limited.

However, it is now a company of 50, and moving yet again to a new headquarters where there are a variety of options for network carriers. The company is known to be growing and three telecommunications companies ("carriers") have been sending sales representatives periodically to inquire if their services might be needed.

With the move to a new facility, some systematic effort must be undertaken to choose an appropriate provider. This becomes a sub-project in its own right, part of the larger program required to effectively complete the move.

As part of this project, a formal "Request for Information" (RFI) is sent to all the potential carriers. Part of this RFI consists of a lengthy series of questions, such as:

* What kinds of circuits are available?
* What is their territory?
* How much data can they handle?
* What do they cost (at a high level)?
* How are they secured?
* How stable are they (how often are they "down")?
* Are co-location services available (can the carrier host the company's servers in its data centers?)
* What other services does the carrier provide?

The responses to these questions are "scored" (assigned a numeric weighting) and the 2 top scoring vendors are issued a Request for Quote (RFQ). The RFQ goes into much more detail in terms of the contract the carrier is willing to offer. After extensive discussions and negotiations, Company X's contract team awards the business to the carrier they believe will provide the greatest value.

The same approach is used to establish relationships with Cloud vendors, software providers, and consultants. In fact, because the approach is so consistent, it is considered a repeatable "process." See the chapter on xref:chap-process-mgmt[process management].

****

A small company may establish binding agreements with vendors relatively casually. For example, when the founder first chose a Cloud platform on which to build their product, they clicked on a button that said "I accept," at the bottom of a lengthy legal document they didn't necessarily read closely. This "clickwrap" agreement is a legally binding contract, which means that the terms and conditions it specifies are enforceable by the courts.

A startup may be inattentive to the full implications of its contracts for various reasons:

* The founder does not understand the importance and consequences of legally binding agreements
* The founder understands, but feels they have little to lose (for example, they have incorporated as a limited liability company, meaning the founder's personal assets are not at risk)
* The service is perceived to be so broadly used that an agreement with it must be safe (if 50 other startups are using a well known Cloud provider and prospering, why would a startup founder spend precious time and money on overly detailed scrutiny of its agreements?)

All of these assumptions bear some risk -- and many startups have been burned on such matters -- but there are many other, perhaps more pressing risks for the founder and startup. See the case study on the xref:9-figure-true-up[9 figure true-up] for a grim scenario.

However, by the time the company has scaled to the team of teams level, contract management is almost certainly a concern of the Chief Financial Officer. The company has more resources ("deeper pockets") and so lawsuits start to become a concern. The complexity of the company's services may require more specialized terms and conditions. Standard "boilerplate" contracts thus are replaced by individualized agreements. Concerns over intellectual property, the ability to terminate agreements, liability for damages, and other topics require increased negotiation and counterproposing contractual language.

At this point, the company may have hired its own legal professional; certainly, legal fees are going up, whether as services from external law firms or internal staff.

Contract and vendor management is more than just establishing the initial agreement. The ongoing relationship must be monitored for its consistency with the contract. If the vendor agrees that its service will be available 99.999% of the time, the availability of that service should be measured and if it falls below that threshhold, contractual penalties may need to be applied.

In larger organizations, where a vendor might hold multiple contracts, a concept of "Vendor Management" emerges. Vendors may be provided "scorecards" that aggregate metrics describing their performance and the overall impression of the customer. Perhaps key stakeholders are internally surveyed as to their impression of the vendor's performance and whether they would be likely to recommend them again. Low scores may penalize a vendor's chances in future RFI/RFP processes; high scores may enhance them.

===== Outsourcing and Cloudsourcing
[quote, Millard et al, Cloud Computing Law]
Classic outsourcing of data processing, for instance payroll processing, involves users giving instructions to agents who are provided with data and tasked with processing the data actively for users according to the user’s mandate.

[quote, Millard et al, Cloud Computing Law]
cloud computing has some fundamental characteristics that distinguish it from traditional outsourcing...many cloud services are merely passive providers of computing resources, utilized by users to perform their own processing.

Software development is only one form of contracted service. Another major class of contract in the modern digital organization is for xref:cloud[Cloud] services.

* Lock-in

Lack of negotiating power on the part of consumers and small businesses has also been a concern. One pillar of the EU’s cloud strategy is the development of model cloud contract terms to cover key issues, such as data preservation after termination, data disclosure and integrity, data location and transfer, ownership of data, direct and indirect liability, change of service by cloud providers, and sub-contracting. 64

Millard, Christopher (2013-10-10). Cloud Computing Law (p. 34). Oxford University Press. Kindle Edition.

7. Insurance as a Tool for Managing Cloud Risks
Insurers may cover cloud users, treating cloud as outsourcing, as many policies covering outsourcing risks may already extend to cloud, or they may insure against specific cloud risks. They may also insure providers in relation to liability to users or others under errors and omissions policies. 65 Insurers may influence the promulgation of best practices among both cloud users and providers, for example by insisting on a security certification as a precondition for cover, or possibly for a pricing discount. The role of insurers in cloud seems set to grow, particularly if stricter legal requirements are imposed on cloud users in future.

Millard, Christopher (2013-10-10). Cloud Computing Law (p. 34). Oxford University Press. Kindle Edition.

===== Software development and contracts

[quote, Agile Manifesto]
Customer collaboration over contract negotiation.

[quote, Andreas Opelt et al, Agile Contracts: Creating and Managing Successful Projects with Scrum]
For both suppliers and buyers of information technology (IT) projects, one issue arises repeatedly: how to get out of the trap of fixed pricing without the disadvantages of time and materials contracts.

[quote, Arbogast et  al, Agile Contracts Primer]
What do lawyers assume is the nature of software projects? First, it is common that they view it as similar to a construction project—relatively predictable—rather than the highly uncertain and variable research and development that it usually is. Second, that in the project (1) there is a long delay before something can be delivered that is well done, with (2) late and weak feedback, (3) long payment cycles, and (4) great problems for the customer if the project is stopped at any arbitrary point in time. *These assumptions are invalidated in agile development.*

Software is often developed and delivered per contractual terms. Contracts are legally binding agreements, typically developed with the assistance of lawyers. As noted in <<Arbogast2012>> (p.5),  "Legal professionals are trained to act, under legal duty, to
advance their client’s interests and protect them against all pitfalls, seen or unseen." The idea of "customer collaboration over contract negotiation" may strike them as the height of naivete. However, Agile and Lean influences have made substantial inroads in contracting approaches.

Arbogast et al. describe the general areas of contract concern:

* Risk, exposure, and liability
* Flexibility
* Clarity of obligations, expectations, and deliverables

They argue that "An agile-project contract may articulate the same limitations of liability (and related terms) as a traditional-project contract, but the agile contract will better support avoiding the very problems that a lawyer is worried about." (p. 12)

So, what is an agile contract?

There are two major classes of contracts:

* Time and materials
* Fixed price

In a *time and materials* contract, the contracting firm simply pays the provider until the work is done. This means that the risk of the project overrunning its schedule or budget resides primarily with the firm hiring out the work. While this can work, there is often a desire on the part of the firm to reduce this risk. If you are hiring someone because they claim they are experts, and can do the work better/cheaper/quicker than your own staff, it seems reasonable that they should be willing to shoulder some of the risk.

In a *fixed price* contract, the vendor providing the service will make a binding commitment that (for example) "we will get the software completely written in 9 months for $3 million." Penalties may be enforced if the software is late, and it's up to the vendor to control development costs. If the vendor does not understand the work correctly, they may lose money on the deal.

Reconciling Agile with fixed-price contracting approaches has been a challenging topic <<Opelt2013>>. The desire for control over a contractual relationship is historically one of the major drivers of xref:1.03.02-Agile-history[waterfall] approaches. However, since requirements cannot be known in advance, this is problematic.

When a contract is signed based on waterfall assumptions, the project management process of xref:change-control[change control] is typically used to govern any alterations to the scope of the effort. Each change order typically implies some increase in cost to the customer. Because of this, the perceived risk mitigation of a fixed price contract may become a false premise.

This problem has been understood for some time. Scott Ambler argued in 2005 that "It's time to abandon the idea that fixed bids reduce risk. Clients have far more control over a project with a variable, gated approach to funding in which working software is delivered on a regular basis" <<Ambler2005>>. Andreas Opelt states, "For agile IT projects it is therefore necessary to find an agreement that supports the balance between a fixed budget (maximum price range) and agile development (scope not yet defined in detail)..."

How is this done? Opelt and his co-authors further argue that the essential question revolves around the project "iron triangle":

* Scope
* Cost
* Deadline

The approach they recommend is determining which of these elements is the "fixed point" and which is estimated. In traditional waterfall projects, scope is fixed, while costs and deadline must be estimated (a problematic approach when xref:2.04.04-lean-product-dev[product development] is required.)

In Opelt's view, in Agile contracting, costs and deadline are fixed, while scope is "estimated" - understood to have some inevitable variability. "...you never know exactly what details will be needed at the start of a project. On the other hand, you do not always need everything that had originally been considered to be important" <<Opelt2013>>.

Their recommended approach supports the following benefits:

* Simplified adaptation to change
* Non-punitive changes in scope
* Reduced knowledge decay (large "batches" of requirements degrade in value over time)

This is achieved through:

* Defining the contract at the level of product or project vision (epics or high-level stories; see discussion of xref:2.0.4.03-scrum[Scrum]) - not detailed specification
* Developing high-level estimation
* Establishing agreement for sharing the risk of product development variability

This last point, which Opelt et al term "riskshare," is key. If the schedule or cost expand beyond the initial estimate, both the supplier and the customer pay, according to some agreed %, which they recommend be between 30%-70%. If the supplier proportion is too low, the contract becomes essentially time & materials. If the customer proportion is too low, the contract starts to resemble traditional fixed-price.

Incremental checkpoints are also essential; for example, the supplier/customer interactions should be high bandwidth for the first few sprints, while culture and expectations are being established and the project is developing a rhythm.

Finally, the ability for either party to exit gracefully and with minimum penalty is needed. If the initiative is testing market response (ala xref:lean-startup[Lean Startup])
and the product hypothesis is falsified, there is little point to continuing the work from the customer's point of view. AND, if the product vision turns out to be far more work than either party estimated, the supplier should be able to walk away  (or at least insist on comprehensive re-negotiation.)

These ideas are a departure from traditional contract management. As Opelt asks, "How can you sign a contract from which one party can exit at any time?" Recall however that (if Agile principles are applied) the customer is receiving working software continuously through the engagement (e.g. after every sprint).

In conclusion, as Arbogas et al argue, "Contracts that promote or mandate
sequential life cycle development increase project risk... an agile approach
... reduces risk because it limits both the scope of the deliverable and extent of the payment [and] allows for inevitable change" (p.13).

===== Software licensing

As software and digital services are increasingly used by firms large and small, the contractual rights of usage become more and more critical.

We mentioned a "clickwrap" licensing agreement above. Software licensing in general is a large and detailed topic, one presenting substantial financial risk to the unwary firm, especially when Cloud and virtualization are concerned.

anchor:9-figure-true-up[]
****
*Case study: The 9-figure "true-up"*
A large enterprise had a long relationship with a major software vendor, who provided a critical software product used widely for many purposes across the enterprise.

The price for this product was set based on the power of the computer running it. A license would cost less for computer with 4 cores and 1 gigabyte of RAM, than it would for a computer with 16 cores and 8 gigabytes of RAM. The largest computers required the most expensive licenses.

As described previously, the goal of xref:virtualization[virtualization] is to use one powerful physical computer to consolidate more lightly-loaded computers as "virtual machines." This can provide significant savings.

Over the course of 3 years, the enterprise described here virtualized about 5,000 formerly physical computers, each of which had been running the vendor's software.

However, a deadly wrinkle emerged in the software vendor's licensing terms. The formerly physical computers were in general smaller machines. The new virtual farms were clusters of 16 of the most powerful computers available on the market. The vendor held that EACH of the 5,000 instances of its software running in the virtual machines was liable for the FULL licensing fee applicable to the most powerful machine!

Even though each of the 5,000 virtual machines could not possibly have been using the full capacity of the virtual farm, the vendor insisted (and was upheld) that the contract did not account for that, and there was no way of knowing whether any given VM had been using the full capacity of the farm at some point.

The dispute escalated to the CEOs of each company, but the vendor held firm. The enterprise was obliged to pay a "true-up" charge of over $100 million (9 figures).

This is not an isolated instance. Major software vendors have earned billions in such charges and continue to audit aggressively for these kinds of scenarios. This is why contracts and licenses should never be taken lightly. Even startups could be vulnerable, if licensed commercial software is used in un-authorized ways in a Cloud environment, for example.

 Steve Russman quote

****

Software licensing is a subset of Software Asset Management, which is itself a subset of IT Asset Management, discussed in more depth in the material on xref:chap-process-mgmt[process management] and xref:IT-lifecycles[IT lifecycles].

 FOSS licensing... risks etc
