==== Project management in the Agile era
[quote, Stanley Portny, Project Management for Dummies 4th ed.]
Projects of all types and sizes are now *the* way that organizations accomplish their work [emphasis added].

[quote, Sriram Narayan, "Scaling Agile: Problems and Solutions"]
...the project as a vehicle of IT execution has by and large, failed to live up to its promise of predictable delivery.

[quote, Charles G. Cobb, The Project Manager's Guide to Mastering Agile: Principles and Practices for an Adaptive Approach]
Agile is having a profound impact on the project management profession and will cause us to fundamentally rethink many of the well-established notions of what a project manager is...

As the above quotes indicate, there are diverse opinions on the role and importance of traditional project management in the enterprise. Clearly it is under pressure from the Agile movement. Project management professionals are advised to not deny or diminish this fact. It is possible for a modern, IT-centric organization to make considerable progress on the basis of xref:2.04.00-product-mgmt[product management] plus simple xref:2.05.00-work-management[work management], without the overhead of the formalized project lifecycle suggested by PMBOK.

Cloud is having related yet distinct impacts on traditional project management as well. As discussed elsewhere, projects were often used to install vendor-delivered commodity software, such as for payroll or employee expense. Increasingly, that kind of functionality is delivered by online service providers, leaving internal IT with considerably reduced responsibilities.

Some of the IT capability may remain in the guise of an internal "service broker," to assist with the sourcing and procurement of online services. The remainder moves into digital product management, as the only need for internal IT is in the area of revenue-generating, market-facing strategic product..

So, a couple questions emerge:

* Given the above, under what circumstances does formalized project management make economic sense?
* Assuming that formalized project management is employed, how does one retain values such as fast feedback and adaptability?

===== Is PM still needed in an Agile, product-centric, Cloud-enabled world?

[quote,  Gary Hamel, preface to the Open Organization: Igniting Passion and Performance]
What’s typically underestimated is the complexity and indivisibility of many large-scale coordination tasks.

[quote, Mark Kennaley, SDLC 3.0]
When risk and uncertainty are present with ongoing demand, like in the case of architectural changes and related high-stake decisions, batching demand into a project for governance reasons makes sense...

====== The organizational view
 Organizational drivers - fair and balanced resource allocation
 graphic: one product vs portfolio of products - PM is the means by which boundaries are established - but long term drawback with relationship to product - there is a portfolio concern in either case

 The project paradigm has a benefit in its explicit timebox and sense of urgency

 A product manager with no project experience will likely fail.

====== The systems view

Kennaley, above, provides some reasoning for project management. Ironically, he uses the term "batch," which is often a concept unfavorably viewed in Agile and Lean circles.

However, when a system presents multiple constraints that need to be solved simultaneously, the only way to do this with confidence may be as a "batch" of thought and analysis. If one needs to balance several competing objectives, one may need to know how a given course of action will affect all of them before embarking. Solving for one constraint, and embarking on a plan of action, may result in not meeting the other constraints, and having to throw the whole solution away.

Dogmatic approaches to solving this are unhelpful.  Multi-constraint optimization is a known hard problem in systems engineering and cannot be wished away through merely invoking the word "Agile."

Not all problems respond to iteration. Iterative solutions may make sense in some cases; in other cases, a higher degree of certainty is required before any solutioning is attempted. Attempting to iteratively refine a given solution may result in completely missing a higher order mode in a complex space (local optimization).

* tactical needs for PM: resources, team performance - see Cohn

* Resource limitations. Schedule limitations (e.g. the critical trade show.)

===== Collaboration at scale
[quote, Mark Kennaley, SDLC 3.0]
Where leveraging yellow stickies or index cards makes sense in conjunction with practices like big visible charts and co-location, such formats become ridiculous for a large constituency of challenging projects . . . When faced with these challenges, rather than proclaim that Agile won't work or doesn't scale, the preferable approach is to understand and acknowledge the nature of collaboration, the nature of distributed workflow, and the complexity of modern product development.

 ultimately, the decision of EA...

===== Agile project management
* Rolling wave planning
* Last responsible moment
* "Water-scrum-fall"

===== Project management antipatterns
* Project change control
* The estimation controversy (sidebar?)
anchor:3.08.03-NoEstimates[]
** "It'll be done when it's done."
* Impersonal requirements ()
* "nothing is real unless it's a project"

===== The Agile project frameworks
* SAFe
* DaD
* etc

===== The future of project management

Recall ultimately our three "Ps":

* Product
* Project
* Process

Taken together, the three represent a coherent set of concerns for value delivery in various forms. But in isolation, any one of them ultimately is limited. This is a particular challenge for project management, whose practitioners may invest deeply in their chosen field of expertise. The field of project management, in turn, has its own expansionist tendencies, to the point where the PMO has become the arbiter of ALL IT investments in some organizations.

A product manager who does not understand the fundamentals of project execution will not succeed...

fundamental theme - what can we know... emergence vs planning ... network vs chain ... finding partial ordering, falsifying hypotheses...

If we "get rid of the PMO" there still is the need to charter new investments. What is their value proposition, business model... there is always a portfolio and some form of success criteria
and there will ALWAYS be issues of resources and dependencies

PERT chart history, Mcnamara, etc

however the days of equating schedule performance with success are ending
or translating EVM directly to the balance sheet (EVM always being a fiction and less and less useful in a digitally transforming world)

Project success: product mgmt happy
Product success: market happy

Sidebar: Practical collaboration at scale (Chapter 7??)
Unmeetings/unconferences
what was that method - some specialists get 300 people together & self organize for objectives --
