==== Why project management?
[quote, Project Management Body of Knowledge, version 5]
A project is a temporary endeavor undertaken to create a unique product, service, or result.

[quote, Project Management Body of Knowledge, version 5]
An ongoing work effort is generally a repetitive process that follows an organization's existing procedures. In contrast, because of the unique nature of projects, there may be uncertainties or differences in the products, services, or results that the project creates.


Limoncelli - IT in old days would spin up a system with a project team and then operate it unchanged 

but now, that kind of functionality is delivered by online service providers -

meaning that more and more internal IT is differentiating and requires those skills

not just "stick some vendor delivered software on a box and run it"

ultimately, the decision of EA...

** basic concerns and disciplines
** PMBOK etc (also covered in Appendix)
** PM relationships w/IT & Agile
*** Impact of Cloud on project management
