anchor:it-sourcing[]

==== IT sourcing
*IT sourcing* is the set of concerns related to identifying suppliers (sources) of the necessary inputs to deliver digital value.

The basic classes of inputs include:

* People (with certain skills and knowledge)
* Hardware
* Software
* Services (which themselves are composed of people, hardware, and/or software)

Practically speaking, these inputs are handled by two different functions:

* People (in particular, full time employees) are handled by a Human Resources function.
* Hardware, software, and services are handled by a Procurement function. Other terms associated with this are Vendor Management, Contract Management, and Supplier Management. We will not attempt to clarify or rationalize these areas in this section.

We will defer the question of people and their skills and knowledge to the next section.

===== Basic concerns

****
*Case study: Choosing a telecommunications provider*

When Company X was a startup, its telecommunications needs were limited, as were its options. The founder had one choice for Internet access, the local cable company. Even when the company moved to a larger space, as a single team startup, its options were limited.

However, it is now a company of 50, and moving yet again to a new headquarters where there are a variety of options for network carriers. The company is known to be growing and three telecommunications companies ("carriers") have been sending sales representatives periodically to inquire if their services might be needed.

With the move to a new facility, some systematic effort must be undertaken to choose an appropriate provider. This becomes a sub-project in its own right, part of the larger program required to effectively complete the move.

As part of this project, a formal "Request for Information" (RFI) is sent to all the potential carriers. Part of this RFI consists of a lengthy series of questions, such as:

* What kinds of circuits are available?
* What is their territory?
* How much data can they handle?
* What do they cost (at a high level)?
* How are they secured?
* How stable are they (how often are they "down")?
* Are co-location services available (can the carrier host the company's servers in its data centers?)
* What other services does the carrier provide?

The responses to these questions are "scored" (assigned a numeric weighting) and the 2 top scoring vendors are issued a Request for Quote (RFQ). The RFQ goes into much more detail in terms of the contract the carrier is willing to offer. After extensive discussions and negotiations, Company X's contract team awards the business to the carrier they believe will provide the greatest value.

The same approach is used to establish relationships with Cloud vendors, software providers, and consultants. In fact, because the approach is so consistent, it is considered a repeatable "process." See the chapter on xref:chap-process-mgmt[process management].

****

A small company may establish binding agreements with vendors relatively casually. For example, when the founder first chose a Cloud platform on which to build their product, they clicked on a button that said "I accept," at the bottom of a lengthy legal document they didn't necessarily read closely. This "clickwrap" agreement is a legally binding contract, which means that the terms and conditions it specifies are enforceable by the courts.

A startup may be inattentive to the full implications of its contracts for various reasons:

* The founder does not understand the importance and consequences of legally binding agreements
* The founder understands, but feels they have little to lose (for example, they have incorporated as a limited liability company, meaning the founder's personal assets are not at risk)
* The service is perceived to be so broadly used that an agreement with it must be safe (if 50 other startups are using a well known Cloud provider and prospering, why would a startup founder spend precious time and money on overly detailed scrutiny of its agreements?)

All of these assumptions bear some risk -- and many startups have been burned on such matters -- but there are many other, perhaps more pressing risks for the founder and startup. See the case study on the xref:9-figure-true-up[9 figure true-up] for a grim scenario.

However, by the time the company has scaled to the team of teams level, contract management is almost certainly a concern of the Chief Financial Officer. The company has more resources ("deeper pockets") and so lawsuits start to become a concern. The complexity of the company's services may require more specialized terms and conditions. Standard "boilerplate" contracts thus are replaced by individualized agreements. Concerns over intellectual property, the ability to terminate agreements, liability for damages, and other topics require increased negotiation and counterproposing contractual language.

At this point, the company may have hired its own legal professional; certainly, legal fees are going up, whether as services from external law firms or internal staff.

Contract and vendor management is more than just establishing the initial agreement. The ongoing relationship must be monitored for its consistency with the contract. If the vendor agrees that its service will be available 99.999% of the time, the availability of that service should be measured and if it falls below that threshhold, contractual penalties may need to be applied.

In larger organizations, where a vendor might hold multiple contracts, a concept of "Vendor Management" emerges. Vendors may be provided "scorecards" that aggregate metrics describing their performance and the overall impression of the customer. Perhaps key stakeholders are internally surveyed as to their impression of the vendor's performance and whether they would be likely to recommend them again. Low scores may penalize a vendor's chances in future RFI/RFP processes; high scores may enhance them.

===== Software licensing

As software and digital services are increasingly used by firms large and small, the contractual rights of usage become more and more critical.

We mentioned a "clickwrap" licensing agreement above. Software licensing in general is a large and detailed topic, one presenting substantial financial risk to the unwary firm, especially when Cloud and virtualization are concerned.

anchor:9-figure-true-up[]
****
*Case study: The 9-figure "true-up"*
A large enterprise had a long relationship with a major software vendor, who provided a critical software product used widely for many purposes across the enterprise.

The price for this product was set based on the power of the computer running it. A license would cost less for computer with 4 cores and 1 gigabyte of RAM, than it would for a computer with 16 cores and 8 gigabytes of RAM. The largest computers required the most expensive licenses, which got to be quite costly.

As described previously, the goal of xref:virtualization[virtualization] is to use one powerful physical computer to consolidate more lightly-loaded computers as "virtual machines." This can provide significant savings.

Over the course of 3 years, the enterprise described here virtualized about 5,000 formerly physical computers, each of which had been running the vendor's software.

However, a deadly wrinkle emerged in the software vendor's licensing terms. The formerly physical computers were in general smaller machines. The new virtual farms were clusters of 16 of the most powerful computers available on the market. The vendor held that EACH of the 5,000 instances of its software running in the virtual machines was liable for the FULL licensing fee applicable to the most powerful machine!

Even though each of the 5,000 virtual machines could not possibly have been using the full capacity of the virtual farm, the vendor insisted (and was upheld) that the contract did not account for that, and there was no way of knowing whether any given VM had been using the full capacity of the farm at some point.

The dispute escalated to the CEOs of each company, but the vendor held firm. The enterprise was obliged to pay a "true-up" charge of over $100 million (9 figures).

This is not an isolated instance. Major software vendors have earned billions in such charges and continue to audit aggressively for these kinds of scenarios. This is why contracts and licenses should never be taken lightly. Even startups could be vulnerable, if licensed commercial software is used in un-authorized ways in a Cloud environment, for example.

 Steve Russman quote

****

Software licensing is a subset of Software Asset Management, which is itself a subset of IT Asset Management, which is discussed in more depth in the material on xref:chap-process-mgmt[process management]
 and xref:IT-lifecycles[IT lifecycles].

===== Impact of Agile

[quote, Agile Manifesto]
Customer collaboration over contract negotiation

Software is often developed and delivered per contractual terms. The desire for control over a contractual relationship is likely one of the major drivers of xref:1.03.02-Agile-history[waterfall] approaches.

===== Impact of Cloud

===== Processes

===== Systems and automation
