=== Chapter 8: Project & Resource Management

[quote, Project Management Body of Knowledge, version 5]
A project is a temporary endeavor undertaken to create a unique product, service, or result.

Project management is traditionally defined as the execution of a given scope of work within constraints of time and budget. As we have seen in our discussions of product management, in implementing truly new IT-based products, estimating time and budget can be difficult because *the necessary information is not available*. In fact, creating it is the actual work of the "project". Therefore, in the new Agile world, there is some uncertainty as to the role and even need for traditional project management.

However, at a practical level, project managers remain important roles and are employed at both "unicorn" and "horse" companies as overall orchestrators of complex initiatives. Financial planning and resource management have not gone away, and without project management financial planning meets challenges, especially regarding the efforts most critical to the business. The very concept of having a vision becomes problematic without some ability to plan.

Because of these interrelated dependencies, this chapter also covers IT financial management, sourcing, and human resource management at an introductory level.

==== Introduction to Chapter 8

===== Chapter 8 outline

* Why project management?
** basic concerns and disciplines
** PMBOK etc (also covered in Appendix)
** PM relationships w/IT & Agile
*** Impact of Cloud on project management

* Project mgmt theory -
** 2 dimensions of demand management
** Critical chain
*** Execution, resource & scheduling constraints
** Last responsible moment

* Project vs product management
** PM still needed in an Agile, product-centric world?
** Project management antipatterns
** The estimation controversy (sidebar?)
** The future of project management

* Sourcing
** Basic concerns
** Impact of Cloud

* Resource management
** Basic concerns
** Impact of Agile
** Time tracking
** SFIA framework

* IT financial management
** Basic concerns
** Agile challenges (Lean Accounting, Beyond Budgeting)

* Topics
** Frameworks
*** What is a framework?
*** PMBOK
*** Frameworks for Agile at scale


===== Chapter 8 learning objectives
* Identify the basic practices of project management
* Understand fundamental concepts of project & execution theory
* Identify the basic concerns of IT resource management
* Identify the basic concerns of IT financial management
