=== Section I Conclusion

We are now at the end of the first section, and one quarter the way through this book (and this course, assuming you are taking a semester long treatment).

You are now the proud master or mistress of a functioning startup. You have decided to provide some product that at least partially depends on an IT-based component that you need to actively develop.

You understand the value that IT brings, and your own product’s needs for it. You have chosen at least a functioning platform for initial development, without falling into the trap of analysis paralysis, although at this point you should be keeping your options open if your initial platform choice doesn’t prove out.

Finally, you have implemented at least a lightweight continuous delivery pipeline. You didn’t need to spend any money doing this, as so much powerful technology is freely available. In particular, from the start you have taken version control very seriously and have a stable, backed up source repository as a basis for your product development.
You also have at least rudimentary systems for tracking requirements, building your software, storing your packages, and deploying them to your production environment.
Congratulations, you’ve got all the basics in place. Your product is starting to attract sales and/or investors, and you’ve hired a few more people. Let’s talk about collaboration.

****
*Staying at Level 1*
In your career, many - perhaps even the majority - of the people you meet and work with will be focused on Level 1 in their thinking and approach.
****

_should we do section I readings/questions?_
