=== Chapter 7: Organization

==== Introduction to Chapter 7
[quote, Alan Turing, Lecture on the Automated Computing Engine -- 1947]
Roughly speaking those who work in connection with the [Automated Computing Engine] will be divided into its masters and its servants. Its masters will plan out instruction tables for it, thinking up deeper and deeper ways of using it. Its servants will feed it with cards as it calls for them. They will put right any parts that go wrong. They will assemble data that it requires. In fact the servants will take the place of limbs... +
 +
As time goes on the calculator itself will take over the functions both of masters and of servants. The servants will be replaced by mechanical and electrical limbs and sense organs… The masters are liable to get replaced because as soon as any technique becomes at all stereotyped it becomes possible to devise a set of instruction tables which will enable the electronic computer to do it for itself…”

You are going through a critical juncture, the "team of teams" transition. You have increasingly specialized people delivering an increasingly complex product, or perhaps even several distinct products. You are in constant discussions around the tension between functional depth versus cross functional delivery.

Many of your employees and consultants emphasize the role of culture, but what do they mean? Is there such a thing as a "good" culture? How is one culture better than another? How can you retain that startup feel you had previously, when things are getting this big?

You often think about how your company should be structured. There is no shortage of opinions there either. From functional centers of excellence to cross-functional product teams, and from strictly hierarchical models to radical models like holacracy, there seems to be an infinite variety of choices.

===== Chapter 7 outline

* Why organization matters
* A simple organizational transformation
* A look at some of Mintzberg's ideas on organization
* A deeper look at product versus function
* Organizational culture
** Rother's research on Toyota Kata

===== Chapter 7 learning objectives

* Distinguish between functional versus product organizations
* Gain an introductory understanding of Mintzberg's "five forces"
* Understand various concepts of culture
