=== Chapter 7: Organization

==== Introduction to Chapter 7

[quote, Steve Denning]
Complexity responds to competence, not authority.

You are going through a critical juncture, the "team of teams" transition. You have increasingly specialized people delivering an increasingly complex product, or perhaps even several distinct products. You are in constant discussions around the tension between functional depth versus cross functional delivery.

Many of your employees and consultants emphasize the role of culture, but what do they mean? Is there such a thing as a "good" culture? How is one culture better than another? How can you retain that startup feel you had previously, when things are getting this big?

You often think about how your company should be structured. There is no shortage of opinions there either. From functional centers of excellence to cross-functional product teams, and from strictly hierarchical models to radical models like holacracy, there seems to be an infinite variety of choices here.

===== Chapter 7 outline

* Why organization matters
* A simple organizational transformation
* A look at some of Mintzberg's ideas on organization
* A deeper look at product versus function
* Organizational culture
** Rother's research on Toyota Kata

===== Chapter 7 learning objectives
*
* Distinguish between functional versus product organizations
* Understand various concepts of culture
