
=== Chapter 5: Work Management

==== Introduction to Chapter 5

NOTE: "Work management" is an unusual title, deliberately chosen to reflect earlier stages of organizational growth. At this point, a fully realized process framework may not be needed, and the organization may not see a need to distinguish precisely between types of work processes. "It's all just work" at this stage.

* What do we need to do?
* In what order?
* Who is doing it?
* Do they need help?
* Do they need direction?
* When will they be done?
* What do we mean by done?

These are fundamental questions for any business larger than a couple co-founders.

You're now a team. You need to get work done. When your startup hired its first employees, and you went from two people to three or four, you almost certainly had to think about this. You are now getting feedback from both your users and product leadership, calling for prioritization, the allocation of resources, and the tracking of effort and completion.

People have different responsibilities and specialties, yet there is a common vision for delivering an IT-based product of some value. How do you keep track of the work? Mostly, you are in the same location, but people sometimes are offsite or keeping different hours. Beyond your product strategy, you have support calls increasingly coming in that result in fixes and new features, and it's all getting complicated.

You already have a product owner. You now institute Scrum practices of a managed backlog, daily standups and sprints. You also use Kanban-style task boards, which are essential for things like support-driven work, but the relationship of these to your Scrum practices is a matter of some ongoing debate. You don't think you need full-blown project management -- yet.

You also may become aware of the idea of "ticketing," if you have people with previous service desk experience. How this relates to your Scrum/Kanban approach is also a question.

===== Chapter 5 outline

* Kanban
** Origins
** Practices
** Visualize
** Limit WIP
** To automate or no?
** Scrum vs Kanban

* Relationship of Scrum to Kanban

* Basic help desk ticketing

* time and space shifting - cadence and synch

* velocity and flow

* A look ahead to more formalized project & process

===== Chapter 5 learning objectives

* Define Kanban and identify its key practices
* Compare and contrast Scrum and Kanban
* Describe task management and synchronization
