anchor:2.05.02-kanban[]

==== Introducing Kanban

To understand Kanban it is advisable to discuss Lean briefly.

Kanban is a term originating from Lean and the Toyota Production System. Originally, it signified a “pull” technique in which materials would only be transferred to a given workstation on a definite signal that the workstation required the materials. This was in contrast to “push” approaches where work was allowed to accumulate on the shop floor, on the (now discredited) idea that it was more “efficient” to operate workstations at maximum capacity.

IMPORTANT: There is a tremendous wealth of material available on Lean history and theory, and the IT student is urged to become familiar with it. +
 +
Historically, there has been resistance in IT circles to learning lessons derived from manufacturing, due to misperceptions that manufacturing is too “repetitive” compared to IT systems development. +
 +
 This resistance is disappearing with the new generation of thought leadership centered on Agile methods and related themes such as DevOps.

David J. Anderson was a product manager at Microsoft who was seeking a more effective approach to managing software development. In consultation with Don Reinertsen (introduced in the http://dm-academy.github.io/aitm/#_lean_lean_product_development_and_don_reinertsen[previous chapter]) he applied the original concept of Kanban to his development activities.<<Anderson2010>>

Unlike Scrum, with its defined, high-pressure sprints, Kanban is a continuous process with no specified cadence. Work is “pulled” from backlog into active attention as resources are freed from previous work.

This is perhaps the most important aspect of Kanban - the idea that work is not accepted until there is capacity to perform it.

You may have a white board covered with sticky notes, but if they are stacked on top of each other with no concern for worker availability, you are not doing Kanban. You are accepting too much work in process and you are likely to encounter a "high-queue state" in which work becomes slower and slower to get done.

There are deeper philosophical and cultural tenets embedded in Kanban beyond workflow. Anderson and his colleagues continue to evolve Kanban into a more ambitious framework. Mike Burrows <<Burrows2014>> identifies the following key principles

* Start with what you do now.
* Agree to pursue evolutionary change.
* Initially, respect current processes, roles, responsibilities, and job titles.
* Encourage acts of leadership at every level in your organization —from individual contributor to senior management.
* Visualize.
* Limit Work-in-Progress (WIP).
* Manage flow.
* Make policies explicit.
* Implement feedback loops.
* Improve collaboratively, evolve experimentally (using models and the scientific method).

 [Reinertsen 204-205 on kanban]

===== Scrum, Kanban, or both?

So, do you choose Scrum, Kanban, both, or neither?

We can see in comparing Scrum and Kanban that their areas of focus are somewhat different.

* Scrum has achieved widespread success and formalization, which is why Scrum training is widespread and generally consistent in content.
* Kanban is seen as more flexible but this comes at a cost of more management overhead. It requires more interpretation to translate to a given organization’s culture and practices.
* “Scrum is not well suited to highly interrupt-driven work.” <<Rubin2012>>. (But if you are too small, it may be difficult to segregate out interrupt-driven work! We will discuss the issues around interrupt-driven work further in Chapter 06.)
* Finally, hybrids exist (Ladas' “Scrumban,” <<Ladas2009>>).

More on this in Section III.

****
*Sidebar: Kanban, process, and respect for people*

Processes cross functions.
Processes (e.g. Quote to Cash, Idea to Production) are what actually deliver value.
We need both process and function; we can’t organize solely around either.
Therefore, get used to matrix management.

The above statements are the management dogma I grew up with. Considered to be innovative at the time, originated by the likes of Michael Hammer and (more rigorously) Geary Rummler. (See Paul Harmon's http://www.bptrends.com/publicationfiles/advisor20081209.pdf[excellent obituary of Geary Rummler].)

But consider a day in the life in the modern corporation: dozens or hundreds of cross functional processes that have become a daily barrage of work on the people housed in the functional areas. Driven by back end automation, front ended by automated (or even manual) email notifications, these required activities include:

* service requests,
* compliance certifications,
* asset validations,
* provisioning requests,
* capacity assessments,
* change approvals,
* training obligations,
* performance assessments,
* audit responses,
* expense reporting,
* travel approvals,

and more - infinitely more. This is the modern, “process"-centric enterprise.

True, any one of these processes is (often) a relatively small burden to perform. Taken together, however, it’s the nightmare of http://www.waywordradio.org/adminisdribble_1/[Adminisdribble]: The daily death by a thousand cuts of required, cross-functional process.

Continual context switching. End to end flow in concept across functions, but little experienced by the multitasking individual. Invisible, unmanaged demand. A thousand channels for flow, but no throughput, because of gridlock.

What drives this? The combination of permanent downsizing, continually increasing governance & compliance burdens, and the assumption that the enterprise can always tolerate another process. Overall organizational capacity is rarely considered, especially for “supporting" processes. And there is no appreciation for the emergent behavior when these myriads of processes interact in unexpected ways.

This is why kanban is so radical. Within a limited scope, it is starting to challenge the IT management dogma at least. User stories, incidents, defects, service requests, changes… they are all “just work.” Just another sticky note on the board. Someone has to perform the work; someone has to allocate time and attention to it. A simple but utterly profound change in orientation. Kanban is the labor movement of the 21st century.

It seems to me that true “respect for people” (as advocated by Lean) of course must start with the recognition that work takes people’s time. I think the modern, process centric enterprise has lost sight of that reality. Is Kanban the answer?

_originally posted at http://www.lean4it.com/2014/08/kanban-vs-process.html_
****
