=== Chapter 10: Security, and Governance, Risk, and Compliance

==== Introduction to Chapter 10

Security threats increase proportionally to the company's size. The talent and persistence of these adversaries is remarkable. Another set of antagonists are, on paper, "on the same side," but auditors are never to be taken for granted. Why are they investigating IT systems? What are their motivations and responsibilities? Finally, what laws and regulations are relevant to IT? Data protection, retention, ?



===== Chapter 10 outline

* Defining architecture
 - Enteprise
 - Business
 - Data
 - Solutions
 - Technical
 * Architecture processes and practices
 * IT governance, risk, compliance

****
Sidebar: Introducing ISACA
****

* Disaster recovery

* Defining governance
* The role of internal audit

_ask Patrick Stachenko to write sidebar on how audit moved into IT_

* Governance, Risk & Compliance as a general space

*  "Rogue" IT



===== Chapter 10 learning objectives
* Identify the basic types of IT architecture
* Describe basic architectural practices
* Characterize some typical challenges for architects
* Define governance vs. management
* Identify common regulatory compliance issues
* Discuss basic security concerns and practices

===== Chapter raw material

CIA

Define vulnerability, threat agent, threat, risk, control, exposure

importance of having the demand/execution framework in place to manage governance demand
