=== Chapter 10: Architecture and governance

==== Introduction to chapter 10

Architecture and governance are two topics that become more important as a company scales up and ages. Decisions that might have been made quickly and casually by a product or project team become more difficult, due to increasingly challenging structural factors both internal and external. Decisions made years ago come back to haunt current strategies with a vengeance. With scale, management needs higher level technical abstractions in order to manage. Architecture provides these, but doing so is difficult and controversial. What happens when management decides to set direction using these same abstractions, and architects find themselves now enforcing what had originally started as mere sense-making?

Vendor relationships become a two-edged sword, providing increased value with access to higher levels of vendor resources, but at the cost of increased lock-in. Pure open-source strategies inevitably become corrupted by business realities.

Security threats increase proportionally to the company's size. The talent and persistence of these adversaries is remarkable. Another set of antagonists are, on paper, "on the same side," but auditors are never to be taken for granted. Why are they investigating IT systems? What are their motivations and responsibilities? Finally, what laws and regulations are relevant to IT? Data protection, retention, ?

* Architecture
 - Also important in next chapter, which can be understood as "advanced architecture"

****
Sidebar: Introducing Open Group and OMG.
****

===== Chapter 10 outline

* Defining architecture
 - Enteprise
 - Business
 - Data
 - Solutions
 - Technical
 * Architecture processes and practices
 * IT governance, risk, compliance

****
Sidebar: Introducing ISACA
****

* Defining governance
* The role of internal audit

 _ask Patrick Stachenko to write sidebar on how audit moved into IT_

* Governance, Risk & Compliance as a general space

*  "Rogue" IT

===== Chapter 10 learning objectives
* Identify the basic types of IT architecture
* Describe basic architectural practices
* Characterize some typical challenges for architects
* Define governance vs. management
* Identify common regulatory compliance issues
* Discuss basic security concerns and practices
