  === Chapter 10: Security, and Governance, Risk, and Compliance

==== Introduction to Chapter 10

Security threats increase proportionally to the company's size. The talent and persistence of these adversaries is remarkable. Another set of antagonists are, on paper, "on the same side," but auditors are never to be taken for granted. Why are they investigating IT systems? What are their motivations and responsibilities? Finally, what laws and regulations are relevant to IT? Data protection, retention, ?

Agile or not, a team ultimately has to meet legal and essential organizational needs, and audits help to ensure this.

Ambler, Scott W.; Lines, Mark (2012-05-31). Disciplined Agile Delivery: A Practitioner's Guide to Agile Software Delivery in the Enterprise (IBM Press) (Kindle Locations 7898-7899). Pearson Education. Kindle Edition.

transforming to an agile delivery approach is difficult. Companies or government agencies that have been in existence for decades have built up layers of deep and wide waste, many of them around governance. Business or IT governance constructs and processes that do not support new technology-centric go-to-market models and products must be either replaced or substantially evolved; otherwise, they increase risk on the agile projects.” (Paul Gorans as quoted in ...)

Ambler, Scott W.; Lines, Mark (2012-05-31). Disciplined Agile Delivery: A Practitioner's Guide to Agile Software Delivery in the Enterprise (IBM Press) (Kindle Locations 8081-8084). Pearson Education. Kindle Edition.

===== Chapter 10 outline


 * IT governance, risk, compliance

****
Sidebar: Introducing ISACA
****

* Disaster recovery

* Defining governance
* The role of internal audit

 _ask Patrick Stachenko to write sidebar on how audit moved into IT_

* Governance, Risk & Compliance as a general space

*  "Rogue" IT

===== Chapter 10 learning objectives
* Identify the basic types of IT architecture
* Describe basic architectural practices
* Characterize some typical challenges for architects
* Define governance vs. management
* Identify common regulatory compliance issues
** Data privacy (pointer to next chapter?)
* Discuss basic security concerns and practices

===== Chapter raw material

CIA

Define vulnerability, threat agent, threat, risk, control, exposure

importance of having the demand/execution framework in place to manage governance demand

We have already covered contracting in terms of software and Cloud. But in terms of the emergence model, it is typical that companies enter into contracts before having a fully mature sourcing and contract management capability with input from the governance, risk, and compliance perspective.
