=== Chapter 10: Architecture and governance

==== Introduction to chapter 10

Architecture and governance are two topics that become more important as a company scales up and ages. Decisions that might have been made quickly and casually by a product or project team become more difficult, due to increasingly challenging structural factors both internal and external. Decisions made years ago come back to haunt current strategies with a vengeance. Vendor relationships become a two-edged sword, providing increased value with access to higher levels of vendor resources, but at the cost of increased lock-in. Pure open-source strategies inevitably become corrupted by business realities.

Security threats increase proportionally to the company's size. The talent and persistence of these adversaries is remarkable. Another set of antagonists are, on paper, "on the same side," but auditors are never to be taken for granted. Why are they investigating IT systems? What are their motivations and responsibilities? 

* Architecture
 - Also important in next chapter, which can be understood as "advanced architecture"

****
Sidebar: Introducing Open Group and OMG.
****

===== Chapter 10 outline

* Defining architecture
 - Enteprise
 - Business
 - Data
 - Solutions
 - Technical

****
Sidebar: Introducing ISACA
****

* Defining governance
* The role of internal audit

 _ask Patrick Stachenko to write sidebar on how audit moved into IT_

* Governance, Risk & Compliance as a general space

===== Chapter 10 learning objectives


