=== Chapter 2: Infrastructure Management

==== Introduction to Chapter 2

ifdef::collaborator-draft[]

_Collaboration notes_

_There is a wealth of material covering IT infrastructure in far more detail than possible here. Curating the most useful aspects for a survey text is the challenge._

_-ctb_

endif::collaborator-draft[]

As mentioned in the section introduction, you cannot start writing code until you choose a programming language, which also has implications for how you ultimately deliver your IT-based product. (You may have a difficult time writing an app for a mobile phone if you choose the COBOL programming language!)

You also need to understand something of how computers are operated, enough so that you can make decisions on how your system will run. Most startups choose to run IT services on infrastructure owned by a Cloud provider, but there are other options.

===== Chapter summary

* Defining "IT infrastructure"
 - How an IT system *runs*, as opposed to what it *does*.
 - The ingredients (OS, language, services)
 - Physical vs virtual
 - Cloud systems
 - Servers vs containers vs services

* IT infrastructure from a management point of view
 - Choosing an infrastructure platform

* Operations overview (brief; covered in depth in http://dm-academy.github.io/aitm/#_chapter_6_operations_management[Chapter 6])

* Automation and infrastructure as code
 - Policy-based approaches

* The critical importance of source control

* Scalability and infrastructure architecture - looking ahead


===== Learning objectives
* Understand fundamental principles of operating computers as infrastructure for a service.
* Understand Cloud as a computing option
* Understand basic principles of "infrastructure as code"
* Understand the importance and basic practices of source code control and why it applies to infrastructure management
