==== Conclusion

Books and articles are written every week about some aspect of IT infrastructure. We have only scratched the surface in our discussions of compute, network, and storage, and how they have become utility services in the guise of Cloud.

Software as a service, platform as a service, infrastructure as a service - each represents a different approach. For the most part, we will focus on Infrastructure as a Service in the remainder of this book, on the assumption that your digital product is unique enough to need the broad freedom this provides.

IT infrastructure is a rich and complex topic, and a person can spend their career specializing in it. For this class, we always want to keep chapter 1 in mind: why do we want it? How does it provide for our needs, contribute to our enjoyment?

===== Discussion questions


===== Research & practice
. Research Cloud providers and recommend which you would prefer to build your new product on.

===== Further reading

* Limoncelli
* Allspaw
* Linux in a Nutshell
* Pro Git
* http://vmboomerang.com/posts/cloud-jumping-why-amazon-aws-is-kicking-paas/
* https://gist.github.com/jboner/2841832[Latency Numbers Every Programmer Should Know]
* http://csrc.nist.gov/publications/nistpubs/800-145/SP800-145.pdf[NIST definition of Cloud computing]
