==== Source control

Now, because this is a general book on IT management, we’re going to take a bit of a different turn here. As mentioned previously, there are numerous sources available to you to learn Linux scripting, policy-based configuration management of infrastructure, and source control. Competency with source control is essential to your career and you should devote some serious time to it. This book has a different purpose: to orient you to the fundamental principles and architectures of IT management at all scales.

We are going to take a very deep and targeted look at source control (aka software configuration management) because it is here that we start to see the emergence of an architecture of IT management. It is in the source control system that we first start to see metadata emerge as an independent concern.

(For a definition of metadata, see the sidebar.)

The concept of a “commit” is a rich foundation for IT management and governance. It both represents the state of the computing system as well as providing evidence of the human activity surrounding it.

As we will see in Chapter 3, the “commit” identifier is directly referenced by build activity, which in turn is referenced by the release activity, which is typically visible across the IT value chain.

Also, the concept of an atomic “commit” is essential to the concept of a “branch” - the creation of an experimental version, completely separate from the main version, so that various alterations can be tried without compromising the overall system stability. Starting at the point of a “commit,” the branched version also becomes evidence of human activity around a potential future for the system. In some environments, the branch is automatically created with the assignment of a requirement or story - again, more on this to come in chapter 3.  In other environments, the very concept of branching is avoided.

ifdef::collaborator-draft[]
_Thought: The concept of a commit is ur-metadata and the foundation of all IT management and governance._
endif::collaborator-draft[]

The concept of a software version control system (variously known as source control, revision control, software configuration management, and other terms) is our first major software system for the “business of IT.” (The virtualization architecture previously discussed is what is under management; the source control system is part of the management architecture.)

The evolution of version control systems to the pivotal role they now hold has been somewhat unexpected. While version control was always deemed important for software artifacts, it has only recently become the preferred paradigm for managing infrastructure state as well.  Because of this, a version control system is easily and without question the first IT management system you should acquire and implement.

(It’s significant that the Agile Alliance indicates “version control” as one of the four foundational areas of Agile, along with team, iterative development, and incremental development.)

*** agile alliance map

So, what is source control?

Source control is like your file system, if it remembered all the changes you make to its contents, and could tell you the differences between any two versions, and also bring back the version you had at any point in time.
Source control, as you may imagine, is critical for any kind of system with complex, changing content, especially when many people are working on that content.

You can find many references to source control on the Internet and in books such as _Pro Git_ by Scott Chacon and Ben Straub. As it is the most important foundational technology for professional IT, whether in a garage or in the largest corporations, you need to have a deep familiarity with it.

Source control is at its most powerful when dealing with symbolic data, which we usually see as text files. It is less useful in dealing with unstructured, binary data, such as image files.

This is because symbolic files can be “differenced” in a way that is meaningful to humans. If I change “abc” to “abd” it is clear that the third character has been changed from “c” to “d.”

On the other hand, if I take a picture (e.g. as a JPEG file) and alter one pixel, and compare the resulting before and after binary files in terms of their data, it would be more difficult to understand what had changed. I would be able to easily tell that they are two different files (they would have different checksums), but they would look very similar.

ifdef::collaborator-draft[]
  *** consider an illustration
endif::collaborator-draft[]

IT starts with symbolic files. Text editors create source code, scripts, and configuration files. These may be transformed in defined ways (e.g. by compilers and build tools) but the human understandable end of the process is mostly based on text files.

We care very much about when a text file changes. One wrong character can completely alter the behavior of a large, complex system. Therefore, our configuration management approach must track to that level of detail.

Although implementation details may differ, all version control systems have some concept of “commit.”
As stated in Version Control with Git:

_In Git, a commit is used to record changes to a repository  . . . Every Git commit represents a single, atomic changeset with respect to the previous state. Regardless of the number of directories, files, lines, or bytes that change with a commit… either all changes apply or none do. In terms of the underlying object model, atomicity just makes sense: A commit snapshot represents the total set of modified files and directories…  Git doesn’t care why files are changing. That is, the content of the changes doesn’t matter. As the developer, you might move a function from here to there and expect this to be handled as one unitary move. But you could, alternatively, commit the removal and then later commit the addition. Git doesn’t care. It has nothing to do with the semantics of what is in the files._

(Loeliger, Jon; McCullough, Matthew (2012-08-14). Version Control with Git: Powerful tools and techniques for collaborative software development (Kindle Locations 1520-1528). O'Reilly Media. Kindle Edition.)

ifdef::collaborator-draft[]
  Discussion of branching & merging?
endif::collaborator-draft[]
