=== Chapter 2: Infrastructure Management

==== Introduction to Chapter 2

As mentioned in the section introduction, you cannot start writing code until you choose a programming language, which also has implications for how you ultimately deliver your IT-based product. (You may have a difficult time writing an app for a mobile phone if you choose the COBOL programming language!)

You also need to understand something of how computers are operated, enough so that you can make a decision on how your system will run. Most startups choose to run IT services on infrastructure owned by a Cloud provider, but there are other options.

===== Chapter summary

* Defining "IT infrastructure"
 - How an IT system *runs*, as opposed to what it *does*.
 - The ingredients (OS, language, services)

* IT infrastructure from a management point of view

* Physical vs virtual

* Cloud systems

* Servers vs containers vs services

****
Sidebar: Introducing Allspaw.
****

* Operations (not too much as that is the topic of Ch 6)

* Automation and infrastructure as code
 - Policy-based approaches

* The critical importance of source control

* Scalability and infrastructure architecture - looking ahead


===== Learning objectives
* Understand fundamental principles of operating computers as infrastructure for a service.
* Understand Cloud as a computing option
* Understand basic principles of "infrastructure as code"
* Understand the importance and basic practices of source code control and why it applies to infrastructure management
