==== Devops and related practices

Consider the Lean Software challenge by Mary and Tom Poppendieck: (***cite)

How long would it take you to change one line of code?

The implicit goal is that the organization should be able to change one line of code, and in fact might want to do so on an ongoing basis.

There is deep Lean/Agile theory behind this goal, theory developed in reaction to the pattern of massive software failures that characterized IT in the first fifty years of its existence.

Achieving this goal is feasible but requires a different approach...

  Applied in an IT setting, a number of practitioners have explored this approach and encountered great success. Key initial milestones included

* The establishment of “test-driven development” as a key best practice in creating software
* Duvall’s book “Continuous Integration”
* Allspaw & X’s seminal “10 Deploys a Day” presentation describing at Etsy
* Humble & Farley’s “Continuous Delivery”

There is a great deal written on the topic of DevOps currently. Some of the most critical practices can be seen by briefly viewing Jez Humble’s Chapter 1 headings for Continuous Delivery:

* Create a Repeatable, Reliable Process for Releasing Software
* Automate Almost Everything
* Keep Everything in Version Control
* If It Hurts, Do It More Frequently, and Bring the Pain Forward
* Build Quality In
* Done Means Released
* Everybody Is Responsible for the Delivery Process
 * Continuous Improvement
(***cite)

Humble’s book is recommended unreservedly.

Let’s go into a little detail on the essential Agile practices.

* Test driven development
* Ongoing refactoring
* Continuous integration
* Continuous deployment
