=== Chapter 3: Application Delivery

ifdef::instructor-ed[]
****
_Instructor's note_
I have opted to defer the "theory" of Agile (as defined by Reinertsen) to Chapter 4. So, this chapter presents Agile and related concepts like iterative development without examining the underlying principles.

I do this because I have discovered that theory sometimes works better in retrospect. Many students increasingly come in with some exposure to Cloud and Agile methods at least, and Chapters 2 and 3 will seem comfortable and familiar. In Chapter 4 we challenge them with *why* Agile works.

****
endif::instructor-ed[]

==== Introduction to chapter 3
Now that we have some idea of IT value (and how we might turn it into a product), and have decided on some infrastructure, we can start building.

IT systems that directly create value for non-technical users are usually called "applications," or sometimes "services." As discussed in chapter 1, they enable value experiences in areas as diverse as consumer banking, entertainment and hospitality, and personal transportation. In fact it is difficult to think of any aspect of modern life untouched by applications. (This overall trend is sometimes called digital transformation.)

Applications are built from software, the development of which is a core concern for any IT-centric product strategy. Software development is a well established career, and a fast-moving field with new technologies, frameworks, and schools of thought emerging weekly, it seems.

This chapter will cover applications and the software lifecycle, from requirements through construction, testing, building, and deployment into modern production environments. It also discusses earlier approaches to software development, the rise of the Agile movement, and its current manifestation in the practice of DevOps.

===== Chapter outline

* What is an "application" (draw on EE, a toaster is an "application" of AC current)
* How applications have been delivered over time
 - How installed
 - How experienced
* Basic application vs service vs software.
* Systems engineering (e.g. complex aerospace hardware/software systems) uses different terminology.

* Application lifecycle

* Earlier software development
 - "Waterfall" that wasn't
 - Project mgmt history under McNamara
* Introduction to Agile proper
 - history, manifesto, etc

 * Introduction to DevOps
  - 10 deploys a day, Phoenix Project, etc

* Application toolchain (source control introduced in prev chapter)
 - Requirements approaches (more on this in chapter 4)
 - Test-driven development
 - Continuous integration
 - Inspections and static analysis
 - Build tool
 - Package repo

* Trends in AD
 - Fast pace of innovation
 - Microservices
 - Re-use & external code

===== Learning objectives

* Define "application" as opposed to "infrastructure"
* Describe the full application lifecycle
* Define "Agile" in terms of software development
* Identify the major components of an end-to-end DevOps delivery pipeline.
