==== Basics of applications and their development

===== Defining "Application"

In keeping with our commitment to theory and first princiles, we use an engineering definition of "application." To an electrical engineer, a toaster or a light bulb is an "application" of electricity. Similarly, a customer relationship management system, or a Web video on demand service, are "applications" of the core computer infrastructure we studied in the last chapter.

===== History of applications

Without applications, computers would be merely a curiousity. Computers were first "applied" to military needs for codebreaking and artillery calculations. After World War II, ex-military officers like Edmund Berkeley at Prudential realized their potential if "applied" to problems like insurance record keeping.

CITES

===== Applications and infrastructure: the old way

In the first decades of computing, any significant appication of computing power to a new problem typically required its own infrastructure, often designed specifically for the problem. While computer scientists always were aware that computers in theory could be "general purpose," in practice this was not so easy. Military/aerospace needs differed from industry, which differed from scientific and technical uses. And major new applications required new compute capacity. So, for example, when a corporation in 1998 decided to replace its mainframe Human Resources system due to https://en.wikipedia.org/wiki/Year_2000_problem[Y2K concerns]. Such a system might need to support several thousand users around the world. At that time, PeopleSoft was a frequent choice of software. Implementing such a system was often led by consulting firms such as Deloitte or Andersen Consulting (where the author worked).

A typical PeopleSoft package implementation would include:

* PeopleSoft software, including the PeopleTools framework and various modules written in the framework (e.g. the well-regarded PeopleSoft HR system)
* Oracle database software
* AT&T "Tuxedo" transaction manager
* Autosys job scheduler
* HP-UX operating system
* HP-UX servers, perhaps 20 or so, comprising various "environments" including a production "cluster" consisting of application and database servers
* EMC storage array
* Various ancillary software and hardware: management utilities and scripts, backup, networking, etc.
* Customization of the PeopleSoft HR module and reports by hired consultants, to meet the requirements of the acquiring organization

The software and hardware needed to be specified in keeping with requirements, and acquiring it took lengthy negotiations and logistics and installation processes. Such a project from inception to production might take 9 months (on the short side) to 18 or more months.

Hardware was dedicated and rarely re-used. The HP servers compatible with PeopleSoft might have few other applications, if they became surplus. In fact, PeopleSoft would "certify" the infrastructure for compatibility. Upgrading the software might require also upgrading the hardware.

===== Applications and infrastructure today
Today, 
