== Section III: Coordination

*Scenario*

You are now a "team of teams," at a size where face to face communication is increasingly supplemented by other forms of communication and coordination. You are seeing more and more specialization in your organization, with the tendency of functional specialists to identify more with their field than with the needs of your customers and your business.

 Your teams are all good, but they are different. They get results, but in different ways. You need some level of coordination and not everyone can talk to everyone; people are no longer co-located and there may be different schedules involved.

You now have multiple products. Some may be external, some may be internal, but they are starting to develop complex interdependencies. Tensions between various teams are starting to emerge. There is an increasing desire among your stakeholders and executives for control and predictability. You are considering various frameworks for managing your organization. This is where it gets hard. 

There are no shortage of contractors and consultants all advocating various flavors of process and project management, some advocating older approaches and "frameworks" and others proposing newer Agile & Lean perspectives. The very concepts of process and project management are occasionally called into question by both your employees and various "thought leaders," and it's all very confusing. Welcome to IT management, circa 2015.

=== Section III introduction

Scenario:

*Chapter 7: Culture and Organization*
 We're getting big.  How are we formally structured? How are people grouped, and to whom do they report, with what kind of expectations? Why this way and not that? Who are we? What are the unspoken assumptions that underly our daily work?

*Chapter 8: Project and Resource Management*
We want to get bigger stuff done. Some argue that we don't need projects at all any more, and it's true that more and more we think in terms of *products* where we used to think of *projects*. But there still is a need to orchestrate the work; even Google and Facebook use project managers. We also have to understand what people are doing on a daily basis. Do we have the right people doing the the work? How can we find the best people to grow our initiative? We also remain concerned that work continues to flow well, that we don't take on too much work in process, and that people are not overloaded and multi-tasking.

*Chapter 9: Process Management*
OK, we have a structure.  Work needs to flow across the structure, and the projects need certain resources and services delivered predictably. Our increasingly specialized organization needs some specialization of processes, and without some kind of coordination  we run the risk of two teams trying to change the same thing at the same time.  We also become specifically concerned with the process by which process is managed, i.e., continuous improvement.
