== Section II: Collaboration

=== Section II introduction

*Scenario*

Your startup has met with some success and you are now a team - still small enough to be fed by two pizzas, if people aren't that hungry. With even with a few new people comes the need to increasingly formalize your product direction, so people are building the right thing. You're all in the same location, and can still easily communicate informally, but there is enough going on that you need more formalized approaches to getting work done. Finally, this great thing you're building doesn't mean much if it's not running right and people can't get to it.

****
Sidebar: Systems theory and idea of feedback
****

*Chapter 4: Product Management*

You (as the startup leader) are spending more time with investors and customers, and maintaining alignment around your original product vision is becoming more challenging as you are pulled in various directions. You need some means of keeping the momentum here.

*Chapter 5: Work Management*

Even with a small team of 5 people (let alone 8 or 9), it's too easy for balls to get dropped as work moves between key contributors. You probably don't need a complex software-based process management tool yet, but you do need some way of managing work in process.

*Chapter 6: Operations Management*

Since Chapter 3, your application developers have been running your systems and even answering the occasional phone call from customers. You're big enough that you need a bit more specialization. You've got dedicated support staff answering the phone calls and you are finding that, even if you rotate operational responsibilities across developers, it is still a distinct kind of "interrupt-driven" work that is not compatible with heads-down, focused software development.
