==== Conclusion

In conclusion, we have considered:

* Why process management matters, and is not likely to go away
* The basics of process description and modeling
* Some background and history of continuous improvement and process control
* The major IT-related process frameworks
* Emerging approaches for digital process management.

As you stand on the threshold of scaling your company yet again, to the enterprise level, you will find process management an essential tool. Like any powerful tool, it has its dangers if misused. Be wary of claims of statistical process control in creative activities, and avoid burdensome process tracking and compliance approaches. Challenge all proposed processes, keep them lean, but if they "make the cut," then make sure everyone knows their existence and status.

===== Discussion questions

. What processes do you experience daily? Weekly?
. Review the section on the xref:spotify-model[Spotify model]. How does it relate to the discussion here?
. Sometimes, organizations try to treat a complex process as defined, instead of managing it empirically. Sometimes, people react by calling this "Taylorism." Why? Google and discuss.
. Have you experienced a problem where an improved process would have helped? What about a problem where process seemed to be the cause of it?

===== Research & practice
. Compare and contrast the Scaled Agile Framework and COBIT.
. Research BPMN notation and use it to document a process familiar to you
. Research process simulation and prepare a report. Optionally, compare process simulation with systems dynamics modeling.
. We know that completely defined processes can be placed under statistical control, and that creative processes cannot be. What about processes falling between these two extremes, such as help desk call management? What does the research say about statistical control of such processes?

===== Further reading

The definitive BPM reference is <<Rummler1995>>. Good practical applications are found in <<Burlton2001>>, <<Harmon2003>>, and <<Sharp2009>>.

The history of Scrum is relevant, in particular <<Schwaber2002>>.

Lean theory is also essential, e.g. <<Womack2003>>, <<Rother2010>>.

Critiques of statistical process control for software are found in <<Binder1997>> and <<Racynski2008>>.

*Books*

* https://www.goodreads.com/book/show/390829.Improving_Performance[Improving Performance: How to Manage the White Space in the Organization Chart]

* https://www.goodreads.com/book/show/1219780.Business_Process_Change[Business Process Change: A Guide for Business Managers and BPM and Six Sigma Professionals]

*Articles*

* http://wwwis.win.tue.nl/~wvdaalst/publications/p712.pdf[Business Process Management: A Comprehensive Survey]

* http://devops.com/2014/11/10/enterprise-devops-doesnt-make-sense/[Why “Enterprise DevOps” Doesn’t Make Sense]

* http://www.computing.dcu.ie/~mcrane/CA441/BPMLectureNotes.pdf[BPM Lecture Notes]

*Videos*

* https://www.youtube.com/watch?v=zGD7-lolujE[Geary Rummler in 1981]

*Professional*

* http://www.bptrends.com/[BPTrends: BPM Analysis, Opinion, and Insight]
* http://www.processrenewal.com/articles-resources/[Process Renewal Group Articles and Resources]
