=== Chapter 9: Process Management

==== Introduction to Chapter 9

No matter what your organization structure, you need process. Toyota considers a clear process vision, or "target condition," to be the most fundamental objective in improving operations. Process, in terms of "business process," has been a topic of study and professional education for many years. Designing processes, improving them, and using them to improve overall  performance is an ongoing activity in most if not all organizations.

However, some less than effective things have been done in the name of "process." Both ITIL and the Capability Maturity Model-Integrated claim to be "process"-oriented, but their results have been questioned. In particular, there is risk in allowing processes to proliferate - the organization can only tolerate a certain number of processes before people start to become confused and demoralized by all the "bureaucracy." Organzational improvement approaches that encourage the formation of processes and associated metrics at all levels may therefore not be an effective model.

Nevertheless, process remains an important tool in the toolkit for organization design.

===== Chapter 9 overview

* Process management basics
 - BPM community
 - Process as a Mintzberg liaison mechanism

****
Sidebar: Can microservices eliminate most or all need for cross-team communication & liaison mechanisms?
****

* Function vs process

* Practice, discipline, capability vs process

* Process and execution (execution includes concern for resource)

* "Process" at Toyota (Rother)

****
Sidebar: Lessons from manufacturing, operations research, etc

Controversy of application to IT

Will this have been foreshadowed?
****

* Self-organizing (kanban) processes vs. formalized process frameworks.

* IT "process" frameworks (ITIL etc - also in appendix)

* Process in product-centric organizations

* Process antipatterns (should I do more with antipatterns in each chapter?)
 - Process proliferation
 - Process without execution model (demand management failure)

* SLAs and the service catalog
** Service-izing functions: pros and cons

****
Sidebar: Quality and Continuous Improvement
****

===== Chapter 9 learning objectives

* Describe a business process and how it crosses functions
* Describe the relationship between business process and business performance
* Describe the origins, purpose, and scope of ITIL and CMMI
* Identify the problems of process proliferation with respect to execution and demand

==== Input material

[quote, Alex Sharp, Workflow Modeling]
One organization enthusiastically embraced process improvement, with good reason: customers, suppliers, and employees found the company's processes slow, inconsistent, and error prone. Unfortunately, they were so enthusiastic that each team defined the work of their small group or department as a complete process. Of course, each of these was in fact the contribution of a specialized functional group to some larger, but unidentified, processes. Each of these "processes" was "improved" independently, and you can guess what happened. +
 +
 Within the boundaries of each process, improvements were implemented that made work more efficient from the perspective of the performer. However, these mini-processes were efficient largely because they had front-end constraints that made work easier for the performer but imposed a burden on the customer or the preceding process. The attendant delay and effort meant that the true business processes behaved even more poorly than they had before. This is a common outcome when processes are defined too "small." Moral: Don't confuse subprocesses or activities with business processes.

If processes are connected on a 1:1 basis, then we say that they are part of a single, end-to-end, business process.

 <<Sharp2009>>

 [Domain modeling]

http://12factor.net/build-release-run

Releases are an append-only ledger and a release cannot be mutated once it is created. Any change must create a new release.

Adapting a services model to improve flow


(Notice that the services a functional area provides can be viewed as a form of product in and of themselves.)


How to structure the matrix

RACI

focus on specific decisions rather than abstract concepts like empowerment and strong vs. weak teams. It is much more useful for teams to know which product features they can change without outside approval than it is to find out they are "empowered."
