==== Topics in process management


===== Cynefin and "best practice"

===== Process antipatterns
Lack of resource awareness for processes (Wells vs Realization)

===== Revisiting the problem of the contending execution models
- Project
- Process
- Product

and the poor "resources" at their intersection, when badly managed.

checklist manifesto submission process for intra communication - great

===== Process flow across a services model

Adapting a services model to improve flow

(Notice that the services a functional area provides can be viewed as a form of product in and of themselves.)

Degree of automation
perils of "take a number" service-ization


===== deeper theory: state charts, Petri nets

===== simulations

 systems dynamics & DES

===== formal process control


****
Sidebar: Can microservices eliminate most or all need for cross-team communication & liaison mechanisms?
****

****
Sidebar: Lessons from manufacturing, operations research, etc

Controversy of application to IT

Will this have been foreshadowed?
****

===== Process and service management
* SLAs and the service catalog
** Service-izing functions: pros and cons

Scenario: repetitive yet error prone work
team to team interactions that become "servicized"

===== The BPM community

* Process antipatterns
 - Process proliferation
 - Process without execution model (demand management failure)
