==== Process management practices
[quote, Don Reinertsen, Managing the Design Factory pp. 197-198]
The first question is, why control the process? When we know why, it almost automatically clarifies how we must control the process. Is a controlled process inherently better than one that has more uncertainty? No. Since the purpose of our process is to make money, it would follow that the purpose of controlling the process must be to influence economic outcomes. There is no other reason to be interested in process control.

===== BPM fundamentals
Grounding in business fundamentals: Porter etc - what organizations *do*

 Practice, discipline, capability vs process

 ordering, synch, conditionality

===== RACI
also seen in general treatments of mgmt, project mgmt, etc - also EA/BizArch

but most refined in process approaches

How to structure the matrix

RACI
focus on specific decisions rather than abstract concepts like empowerment and strong vs. weak teams. It is much more useful for teams to know which product features they can change without outside approval than it is to find out they are "empowered."

reinertsen has stuff on this

===== Process granularity
[quote, Alex Sharp, Workflow Modeling]
One organization enthusiastically embraced process improvement, with good reason: customers, suppliers, and employees found the company's processes slow, inconsistent, and error prone. Unfortunately, they were so enthusiastic that each team defined the work of their small group or department as a complete process. Of course, each of these was in fact the contribution of a specialized functional group to some larger, but unidentified, processes. Each of these "processes" was "improved" independently, and you can guess what happened. +
 +
 Within the boundaries of each process, improvements were implemented that made work more efficient from the perspective of the performer. However, these mini-processes were efficient largely because they had front-end constraints that made work easier for the performer but imposed a burden on the customer or the preceding process. The attendant delay and effort meant that the true business processes behaved even more poorly than they had before. This is a common outcome when processes are defined too "small." Moral: Don't confuse subprocesses or activities with business processes.

If processes are connected on a 1:1 basis, then we say that they are part of a single, end-to-end, business process.

 <<Sharp2009>>


====== Case Management

===== Process vs execution (execution includes concern for resource)

====== Decision rules
 Reinertsen Boeing case

Rule engines

===== Cynefin and the Checklist Manifesto
  The problem of determinism
  Required interactions as well as required steps
  Process as a Mintzberg liaison mechanism

===== Deeper theory

http://blogs.forrester.com/jean_pierre_garbani/09-06-26-my_issue_itil

CPRET is a mnemonic for the basic definition of process in process engineering: it stands for Constraints, Product, Resources, input Elements and Transformation which are the basic components of a process. In process engineering, a process is a suite of transformations of elements into a given output (product) given a set of constraints and resources. From this definition, we can see that technology has a strong influence on the process: the transformation part is a clear function of the technology available as input and resources in IT are strongly influenced by the technology used. As we mostly deal with information and data in IT management processes, the type of data available is either helping or impeding the transformation part.

Schwaber process author - chem e guy

Kennelay - PID model



* "Process" at Toyota (Rother)
