
anchor:frameworks[]

==== Process frameworks
ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is in development as of 8 Jun 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

So, what is a "framework?"

The term "framework," in the context of business process, is used for comprehensive and systematic representations of a major business area's activities. The first goal of any framework is, for a given conceptual space, to provide a "map" of its components and their relationships. Doing this serves a variety of goals:

* Develop and support professional consensus on the business area
* Support training and orientation of professionals new to the area (or its finer points)
* Support governance and control activities related to the area



Many framewo rks have em erged to help und er-
stand the overall problem . (See th e section "What is a process fram ewo rk ?"
earlier in this chapter.) The three major fram ewo rks hav ing th e most effect
on enterprise IT in th e United States at this writing are CO Brr"', CMMI " ,
and ITIL "', altho ugh there are other public and semi pub I ic fram ewo rks such
as the App lication Services Library, Business In formation Servi ces Library,
and Info rm ati o n Systems Procurem ent Libra ry, as well as less formalized pub-
lish ing ho use li braries and propri etary fram eworks owned by th e major consul-
tancies and research firms .
COB IT<8>, ITIL <8>, and CMM I<8> provide significant perspecti ves o n major o ngoing
capabil ities and fun ctions th at the large IT o rgan iza tion must perform and in
general are developed fro m the perspective of steady-state functi o ns, as o pposed
to a value strea m or rigorous process perspective. (Agai n, revi ew lheir major
concepts and ask yo urself which are "countable." ) Alo ng with the value stream
ana lys is presented in th e previo us cha pter, they serve as useful statem ents of
requirem ents for the data, system , and pattern analysis in the next chapters.

In closing, IT capability frameworks can be harmful if they lead to fragmen-
tation of improvement effort and lack of focus on the flow of IT value. In
the imagery of Eli Goldratt, the problem with CMMI@, COBIT®, and mL <II>
is that they do not help you find the heavy Boy Scout. They don't point
you towards the IT equivalent of the $2 million computerized machine
tool that actually reduced the plant's profitability. And it seems likely that
large-scale IT might be vulnerable to such constraints.


===== Continuous improvement frameworks

===== IT management frameworks

====== Process vs function in the frameworks

====== ITIL

====== COBIT

====== TOGAF

====== IT4IT

====== The particular case of CMMI

Process capability is the
inherent variation of the process in relation to the specification limits. The smaller
the process variation, the better the process's capability. <<Kan1995>>

===== Process "Maturity" and "quality"

what is maturity? Cooke-Davis defines this as "the extent to which an organization has explicitly and consistently deployed processes that are documented, managed, measured, controlled, and continually improved" (Cooke-Davies, 2004). <<Richardson2010>>

====== Other frameworks
