==== Topics in process management


===== Cynefin and "best practice"

===== Process antipatterns
Lack of resource awareness for processes (Wells vs Realization)

===== Revisiting the problem of the contending execution models
- Project
- Process
- Product

and the poor "resources" at their intersection, when badly managed.

checklist manifesto submission process for intra communication - great

===== Process flow across a services model

Adapting a services model to improve flow

(Notice that the services a functional area provides can be viewed as a form of product in and of themselves.)

Degree of automation
perils of "take a number" service-ization


===== deeper theory: state charts, Petri nets

===== BPMN, BPEL, and more

===== simulations

 systems dynamics & DES

===== Deeper theory 

 http://blogs.forrester.com/jean_pierre_garbani/09-06-26-my_issue_itil

 CPRET is a mnemonic for the basic definition of process in process engineering: it stands for Constraints, Product, Resources, input Elements and Transformation which are the basic components of a process. In process engineering, a process is a suite of transformations of elements into a given output (product) given a set of constraints and resources. From this definition, we can see that technology has a strong influence on the process: the transformation part is a clear function of the technology available as input and resources in IT are strongly influenced by the technology used. As we mostly deal with information and data in IT management processes, the type of data available is either helping or impeding the transformation part.

 Schwaber process author - chem e guy

 Kennelay - PID model
===== formal process control


****
Sidebar: Can microservices eliminate most or all need for cross-team communication & liaison mechanisms?
****

****
Sidebar: Lessons from manufacturing, operations research, etc

Controversy of application to IT

Will this have been foreshadowed?
****

===== Process and service management
* SLAs and the service catalog
** Service-izing functions: pros and cons

Scenario: repetitive yet error prone work
team to team interactions that become "servicized"

===== The BPM community

* Process antipatterns
 - Process proliferation
 - Process without execution model (demand management failure)
