
anchor:frameworks[]

==== Process frameworks
ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is in development as of 8 Jun 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

===== Defining frameworks

NOTE: There are other usages of the term "framework," especially in terms of software frameworks. Process and management frameworks are non-technical.

So, what is a "framework?"

The term "framework," in the context of business process, is used for comprehensive and systematic representations of a major business area's activities. In general, an industry framework is structured artifact that seeks to articulate a professional consensus regarding a domain of practice. The intent is usually that the guidance be mutually exclusive and collectively exhaustive within the domain, so that persons knowledgeable in the framework have a broad understanding of domain concerns.

The first goal of any framework is, for a given conceptual space, to provide a "map" of its components and their relationships. Doing this serves a variety of goals:

* Develop and support professional consensus on the business area
* Support training and orientation of professionals new to the area (or its finer points)
* Support governance and control activities related to the area

Many frameworks have emerged in the IT space, with broader and narrower domains of concern. Some are owned by non-profit standards bodies; others are commercial. We will focus on five in this book:

* ITIL (originally the Information Technology Infrastructure Library)
* COBIT (aka Control Objectives for Information Technology)
* TOGAF (The Open Group Architecture Framework)
* PMBOK (The Project Management Body of Knowledge)
* CMMI (Capability Maturity Model-Integrated)
IT capability frameworks can be harmful if they lead to fragmentation of improvement effort and lack of focus on the flow of IT value.

====== ITIL
*ITIL,* originally the Information Technology Infrastructure Library, is a publication of the UK government, now via the Axelos commercial joint venture with Capita Group. It is in its 4th major edition (2011). While often considered an “operational” framework, ITIL spans the lifecycle of IT services and systems, from Strategy to Design to Transition to Operations to Continual Service Improvement. However, due to the particular structure of UK government publications, ITIL does not cover project management or the SDLC per se, or analysis, architecture and design.

ITIL is a lengthy and expensive to obtain publication, containing about 2000 pages of narrative guidance covering 26 processes and additional IS/IT functions and activities, from IT Finance to Event Management.

====== COBIT
*COBIT,* originally the Control Objectives for Information Technology, is a set of guidance from the IS Audit and Control Association. It has a broader scope than ITIL, as it includes architecture and project management. Where ITIL contains narrative of considerable length, COBIT is terser and more structured, providing a useful framework for the construction and testing of suitable controls for IT governance.

COBIT can be freely accessed through www.isaca.org.

====== TOGAF
*TOGAF,* or The Open Group Architecture Framework, is a framework and method for IT and enterprise architecture practices.

TOGAF can be freely accessed through www.opengroup.org

====== PMBOK
*PMBOK,* or the Project Management Body of Knowledge, is a publication of the Project Management Institute. It represents the codification of formal project management knowledge. There is a comparable Axelos publication, Prince2, not covered here. PMBOK was covered in Chapter 8.

====== The particular case of CMMI
Process capability is the inherent variation of the process in relation to the specification limits. The smaller the process variation, the better the process's capability. <<Kan1995>>

what is maturity? Cooke-Davis defines this as "the extent to which an organization has explicitly and consistently deployed processes that are documented, managed, measured, controlled, and continually improved" (Cooke-Davies, 2004). <<Richardson2010>>

====== Other frameworks
Many other frameworks exist, under varying governance models from open to proprietary. An up to date list is maintained by Van Haren Publishing in their publication Global Standards and Publications (Van Haren Publishing, 2016). A variety of Agile frameworks also have formed, which will be discussed separately. Finally, there is a broad ecosystem of vendor-specific certifications as well, to educate practitioners in the specifics of various commercial products.

===== Pros and cons of the frameworks

Process vs function in the frameworks
All of these frameworks provide notable descriptions of major ongoing capabilities and functions that the large IT organization must perform. They in general are developed from the perspective of steady-state functions, as opposed to a value stream or defined process perspective.
