==== Why process management?
[quote, Don Reinertsen, Managing the Design Factory pp. 197-198]
The first question is, why control the process? When we know why, it almost automatically clarifies how we must control the process. Is a controlled process inherently better than one that has more uncertainty? No. Since the purpose of our process is to make money, it would follow that the purpose of controlling the process must be to influence economic outcomes. There is no other reason to be interested in process control.

Process management starts with the fundamental capability for coordinated xref:2.05.00-work-management[work management], and refines it much further.

Work will have already been specializing. Sales process, HR process, etc. This is about a certain degree of formalization that includes explicit process improvement.

Scenario: repetitive yet error prone work
team to team interactions that become "servicized"

from work to process mgmt

A glance at the frameworks? At least examples are needed.

===== The fundamental point
The digital service *is* fundamentally an automated process. That's what computers do.


===== Process vs work management
kanban board starts to elaborate

Ordered tasks are something we've had since Chapter 5. Process management is when we need to start managing multiple processes and considering their interdependencies, perhaps using common engines and methods to define them.

"there are many organizational processes that are needed to optimally support a successful project." <<Richardson2010>>

checklist... wait, didn't we see that in Project Mgmt?

the difference is that in PM, the checklist is usually re-created every time. Process mgmt re-uses.

* Self-organizing (kanban) processes vs. formalized process frameworks.

===== Process vs function
Will functions stay with product centricity?

Need an overall concept of product/project/process

<<Cohn2010>> p144 assumes functional mgrs will stay

perils of "take a number" service-ization

Measuring process. KPIs across a 36-process operating model?

===== Self-organization and process
Control vs ...

* "Process" at Toyota (Rother)

===== "Business" vs "IT" process

===== Process in the product-centric organization
