==== Agile and IT process management
Manifesto quote

===== Process management in the organization


Will functions stay with product centricity?

Binary thinking - Stroustrup quote. 

===== Self organization?

* Self-organizing (kanban) processes vs. formalized process frameworks.

===== Bureaucratic friction
[quote, Mike Cohn]
"Many companies have at least one dysfunctional area. This may be the “furniture police” who won’t let programmers rearrange furniture to facilitate pair programming. Or it may be a purchasing group that takes six weeks to process a standard software order. In any event these types of insanity get in the way of successful projects. One way to view the project manager is as the bulldozer responsible for quickly removing these problems."

 example of service-ized process dysfunction
 is expediting the only option?
 alternatives...

===== Failure of CASE
past a certain point of complexity (especially in event driven systems) nodes and edges do not work.

orchestration vs choreography

===== Agile modeling (Ambler)

===== Failure of CMM

===== The design factory problem
Misunderstanding variation

===== Process as a source of demand/resource

===== Cost of delay of aggregate process

===== Cultural aspects
overcome through rational, specific understanding of concepts like cadence and synch

 Invariants
 Process is "adaptive" only to a degree
 Standard + case

 Scrum of scrums as a synch point


 Cost of delay & process cycles

"It will be seen that the cost of a process on a single part becomes a perfectly definite and tangible thing and can be recorded as such." Church quoted in <<Huntzinger2007>> p 85



Richard Knaster, IBM Rational’s worldwide agile practice manager, has helped several organizations to scale agile. He reports: “Development intelligence strategies such as automated dashboards are excellent tools to steer projects and ensure that agile teams are working effectively. In large organizations where there are many projects the physical space and governance needs make the use of whiteboards to track projects (e.g., taskboards, burndown charts) unfeasible. Management cannot be expected to attend ten or more daily meetings to understand if the projects responsible for their strategy execution are on track. A large insurance company found that by using IBM Rational Team Concert (RTC) dashboards they could easily see how well projects were progressing towards their release goals and if the agile practices that they had adopted were being followed correctly. By looking at the dashboards, they discovered that some teams were not writing stories effectively, nor concluding the iteration by either marking stories as being done or moving incomplete stories to the next iteration or to the product backlog. The dashboards also helped them get a handle on their technical debt. It was easy to view the defect trend for a single team or for the entire enterprise and understand if the teams were addressing quality throughout the projects or just towards the end of the release. The insurance company was also able to see whether the team was tracking impediments, performing retrospectives, and taking a few key actions from the retrospectives.”

Ambler, Scott W.; Lines, Mark (2012-05-31). Disciplined Agile Delivery: A Practitioner's Guide to Agile Software Delivery in the Enterprise (IBM Press) (Kindle Locations 8337-8348). Pearson Education. Kindle Edition.

 checklist manifesto
