anchor:continuous-improvement[]

==== Continuous improvement

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is in process as of June 4, 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

[quote, Don Reinertsen, Managing the Design Factory pp. 197-198]
The first question is, why control the process? When we know why, it almost automatically clarifies how we must control the process. Is a controlled process inherently better than one that has more uncertainty? No. Since the purpose of our process is to make money, it would follow that the purpose of controlling the process must be to influence economic outcomes. There is no other reason to be interested in process control.


===== The question of variation

First, there is a long-standing management interest in variability. What do we mean by this?

If you expect a process to take 5 days, what do you make of occurrences when it takes 7 days? 4 days? If you expect a manufacturing process to yield 98% usable product, what do you do when it falls to 97%? 92%?

Analyzing such "variation" has been a part of management technique for decades, and is an important part of disciplines such as Six Sigma.


what is maturity? Cooke-Davis defines this as "the extent to which an organization has explicitly and consistently deployed processes that are documented, managed, measured, controlled, and continually improved" (Cooke-Davies, 2004). <<Richardson2010>>

In the world of agile delivery the role of quality assurance needs to adapt from auditing the quality of the process and product that is delivered at the end of the lifecycle to supporting practices that ensure that quality is built in and validated from the beginning of the project.

Ambler, Scott W.; Lines, Mark (2012-05-31). Disciplined Agile Delivery: A Practitioner's Guide to Agile Software Delivery in the Enterprise (IBM Press) (Kindle Locations 8175-8177). Pearson Education. Kindle Edition.


 Kaizen and kamikaze kaizen
