
anchor:frameworks[]

==== Process frameworks
ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is in development as of 8 Jun 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

===== Defining frameworks

NOTE: There are other usages of the term "framework," especially in terms of software frameworks. Process and management frameworks are non-technical.

So, what is a "framework?"

The term "framework," in the context of business process, is used for comprehensive and systematic representations of a major business area's activities. In general, an industry framework is structured artifact that seeks to articulate a professional consensus regarding a domain of practice. The intent is usually that the guidance be mutually exclusive and collectively exhaustive within the domain, so that persons knowledgeable in the framework have a broad understanding of domain concerns.

The first goal of any framework is, for a given conceptual space, to provide a "map" of its components and their relationships. Doing this serves a variety of goals:

* Develop and support professional consensus on the business area
* Support training and orientation of professionals new to the area (or its finer points)
* Support governance and control activities related to the area

Many frameworks have emerged in the IT space, with broader and narrower domains of concern. Some are owned by non-profit standards bodies; others are commercial. We will focus on five in this book. In roughly chronological order, they are:

* CMMI (Capability Maturity Model-Integrated)
* ITIL (originally the Information Technology Infrastructure Library)
* PMBOK (The Project Management Body of Knowledge)
* COBIT (aka Control Objectives for Information Technology)
* TOGAF (The Open Group Architecture Framework)

A 6th framework, IT4IT, will be discussed in Chapter 12.

====== CMMI
The Capability Maturity Model was originally published by Watts Humphrey in 1989 in the book _Managing the Software Process_ <<Humphrey1989>>. Humphrey's original vision was to apply full statistical process control to the software process. As he stated at the time:

_Dr. W. E. Deming, in his work with the Japanese after World War II, applied the concepts of statistical process control to many of their industries. While there are important differences, these concepts are just as applicable to software as they are to producing consumer goods like cameras, television sets, or auto
mobiles._

The CMM was later taken on by the Software Engineering Institute at Carnegie-Mellon University, and is now managed by the CMMI Institute at Carnegie-Mellon.

The CMM has had considerable influence on software development and IT management more generally. It popularized the idea that process management tends to evolve in the same way across organizations, following a "staged" model:

Stage 1: Initial

Stage 2: Repeatable

Stage 3: Defined

Stage 4: Managed

Stage 5: Optimizing

(These are Humphrey's original levels. There are some differences with the current CMMI, but the concept is the same.)

These ideas can be seen reflected in later guidance such as COBIT and ITIL.

Within this overall framework of maturation, CMMI currently calls for 22 process areas:

* Causal Analysis and Resolution (CAR)
* Configuration Management (CM)
* Decision Analysis and Resolution (DAR)
* Integrated Project Management (IPM)
* Measurement and Analysis (MA)
* Organizational Process Definition (OPD)
* Organizational Process Focus (OPF)
* Organizational Performance Management (OPM)
* Organizational Process Performance (OPP)
* Organizational Training (OT)
* Product Integration (PI)
* Project Monitoring and Control (PMC)
* Project Planning (PP)
* Process and Product Quality Assurance (PPQA)
* Quantitative Project Management (QPM)
* Requirements Development (RD)
* Requirements Management (REQM)
* Risk Management (RSKM)
* Supplier Agreement Management (SAM)
* Technical Solution (TS)
* Validation (VAL)
* Verification (VER)

The overall idea is that a process cannot be improved and optimized until it is fully under control. As we discussed in the previous section, this may be true for defined processes, but  process theorists see creative, knowledge-intensive processes as requiring empirical control.

In CMM terms, empirical processes start by measuring and immediately optimizing. They need not -- cannot -- be fully defined. One of the most questionable aspects of CMM, is its framing process optimization as something only done at the highest levels of maturity.

This runs counter to much current thinking and practice, especially that deriving from Lean philosophy, in which processes are seen as always under improvement. (See discussion of xref:Toyota-Kata[Toyota Kata]
.) All definition, measurement, and control serve that end.

The CMMI has evolved since Humphrey's initial vision, but retains an emphasis on statistical process control that (in the view of this author) seems increasingly out of step with the reality of the new digital economy.

====== ITIL
About the same time as the CMM's initial creation and transition to the Software Engineering Institute, the Central Computer and Telecommunications Agency of the United Kingdom recognized that IT practices were becoming fragmented. In response, a multi-volume set of guidance known as the IT Infrastructure Library was created. A 2nd edition consolidated and updated this guidance, and achieved worldwide acceptance as a de facto standard for IT management. The term "service" was inserted, i.e. "IT Service Management" but the distinction between the ITSM term and simple "IT Management" has always been somewhat unclear.

Due to the particular structure of UK government publications, ITIL has never covered project management or the SDLC per se, or analysis, architecture and design.

ITIL is currently published via the Axelos commercial joint venture between the UK government and Capita Group. It is now in its 4th major edition (2011). While often considered an “operational” framework, ITIL spans the lifecycle of IT services and systems; the current volumes reflect a lifecycle:

* Service Strategy
* Service Design
* Service Transition
* Service Operations
* Continual Service Improvement

Within these volumes, ITIL defines a number of activities, functions, and what it calls processes (more on this below). These definitions have helped stabilize industry practice and  provided a basis for industry training and certification of individuals.

ITIL's processes include:

[cols="2,6", options="header"]
|====
|ITIL Stage|Processes
|Service Strategy
|Strategy Management for IT Services +
Service Portfolio Management +
Demand Management +
Financial Management for IT Services +
Business Relationships Management +
|Service Design
|Design Coordination +
Service Catalogue Management +
Service Level Management +
Risk Management +
Capacity Management +
Availability Management +
IT Service Continuity Management +
Information Security Management +
Compliance Management +
Architecture Management +
Supplier Management +
|Service Transition
|Change Management
Change Evaluation +
Project Management (Transition Planning and Support) +
Application Development +
Release and Deployment Management +
Service Validation and Testing +
Service Asset and Configuration Management +
Knowledge Management +
|Service Operation
|Event Management +
Incident Management +
Request Fulfillment +
Access Management +
Problem Management +
IT Operations Control +
Facilities Management +
Application Management +
Technical Management +
|Continual Service Improvement
|Service Review +
Process Evaluation +
Definition of CSI Initiatives +
Monitoring of CSI Initiatives +
|====

====== PMBOK
The Project Management Body of Knowledge, is a publication of the Project Management Institute. It represents the codification of formal project management knowledge. There is a comparable Axelos publication, Prince2, not covered here. PMBOK was covered in xref:PMBOK[Chapter 8].

====== COBIT
COBIT, originally the Control Objectives for Information Technology, is a set of guidance from the IS Audit and Control Association. It has a broader scope than ITIL, as it includes architecture and project management.

Where ITIL contains narrative of considerable length, COBIT is more terse and structured, providing a useful framework for the construction and testing of suitable controls for IT governance.

[cols="2,6", options="header"]
|====
|CObIT Domain|Processes
|Plan and Organize (PO)
|PO1 Define a strategic IT plan +
PO2 Define the information architecture +
PO3 Determine technological direction +
PO4 Define the IT processes, organization and relationships +
PO5 Manage the IT investment +
PO6 Communicate management aims and direction +
PO7 Manage IT human resources +
PO8 Manage quality +
PO9 Assess and manage IT risks +
PO10 Manage projects +
|Acquire and Implement (AI)
|AI1 Identify automated solution +
AI2 Acquire and maintain application software +
AI3 Acquire and maintain technology infrastructure +
AI4 Enable operation and use +
AI5 Procure IT resources +
AI6 Manage changes +
AI7 Install and accredit solutions and changes +
|Deliver and Support (DS)
|DS1 Define and manage service levels +
DS2 Manage third-party service +
DS3 Manage performance and capacity +
DS4 Ensure continuous service +
DS5 Ensure systems security +
DS6 Identify and allocate costs +
DS7 Educate and train users +
DS8 Manage service desk and incidents +
DS9 Manage the configuration +
DS10 Manage problems +
DS11 Manage data +
DS12 Manage the physical environment +
DS13 Manage operations +
|Monitor and Evaluate (ME)
|ME1 Monitor and evaluate IT performance. +
ME2 Monitor and evaluate internal control. +
ME3 Ensure compliance with external requirements. +
ME4 Provide IT governance +
|====

COBIT can be freely accessed through www.isaca.org.

====== TOGAF
The Open Group Architecture Framework, is a framework and method for IT and enterprise architecture practices. TOGAF advocates an "Architecture Development Method" consisting of:

* Architecture Vision
* Business Architecture
* Information Systems Architectures
* Technology Architecture
* Opportunities and Solutions
* Migration Planning
* Implementation, Governance
* Architecture Change Management

TOGAF can be freely accessed through www.opengroup.org.

We will discuss architecture more in Chapter 12.

====== Other frameworks
Many other frameworks exist, under varying governance models from open to proprietary. An up to date list is maintained by Van Haren Publishing in their publication Global Standards and Publications (Van Haren Publishing, 2016). A variety of Agile frameworks also have formed, which will be discussed separately. Finally, there is a broad ecosystem of vendor-specific certifications as well, to educate practitioners in the specifics of various commercial products.

===== General observations on the frameworks
We have discussed the problems of process control with respect to the CMM and CMMI in particular. While the other frameworks seem more cautious in their approach to variation,there are a variety of other concerns with respect to them:

* Local optimization temptation
* Confusion of process definition
* Lack of execution model
* Large batch orientation

====== Local optimization temptation

IT capability frameworks can be harmful if they lead to fragmentation of improvement effort and lack of focus on the flow of IT value.

The digital delivery system at scale is a complex socio-technical system, including people, process, and technology. Frameworks help in understanding it, by breaking it down into component parts in various ways. This is all well and good, but the danger of *reductionism* emerges.

NOTE: There are various definitions of "reductionism." This discussion reflects one of the more basic versions.

A reductionist view implies that a system is nothing but the sum of its parts. Therefore, if each of the parts is attended to, the system will also function well.

This can lead to a compulsive desire to do "all" of a framework. If ITIL calls for 25 processes, then a large, mature organization by definition should be good at all of them. But the 25 processes (and dozens more sub-processes and activities) called for by ITIL are somewhat arbitrary divisions. They overlap with each other. Furthermore, there are many digital organizations that do not use the full ITIL process portfolio and yet deliver value as well as organizations that do use ITIL. (Most Silicon Valley startups avoid process framworks, even when they scale up.)

====== Confusion of process definition

Another issue with the "process" frameworks is that, while they use the word "process" prominently, they are not aligned with Business Process Management best practices. <<Betz2011b>>

All of these frameworks provide notable descriptions of major ongoing capabilities and functions that the large IT organization must perform. They in general are developed from the perspective of steady-state functions, as opposed to a value stream or defined process perspective.

This can be seen by looking above at ITIL, for example. A Business Process Management consultant would see the term "Capacity Management" and observe that it is not countable or event-driven. "How many Capacities did you do today," might be the question.

====== Lack of execution model
However, specifying too many event-driven processes has its own complications. Both ITIL and COBIT devote considerable time to documenting possible process inputs and outputs. But processes do not run themselves. These process handoffs require staff attention. They impose demand on the system.

We have discussed the issue of overburden previously. Too many organizations have contending execution models, where projects, processes, and miscellaneous work all compete for people's attention. In such environments, the overburden and wasteful multi-tasking can reach crisis levels.

====== Large batch orientation
Finally, even if a given process framework does not specifically call for waterfall, one can sometimes still see its legacy. Calls for thorough project planning and estimation, heavy documentation requirements, and so forth can signal a large batch orientation even in frameworks making some claim of supporting Agile.

In the next chapter on Agile process management, we'll consider these and further issues with process management in general, and some current  responses consistent with current digital approaches.
