==== Topics in process management

===== The complex relationship of process and Agile

===== Cynefin and "best practice"

===== Process antipatterns
Lack of resource awareness for processes (Wells vs Realization)

===== Revisiting the problem of the contending execution models
- Project
- Process
- Product

and the poor "resources" at their intersection, when badly managed.

checklist manifesto submission process for intra communication - great


Richard Knaster, IBM Rational’s worldwide agile practice manager, has helped several organizations to scale agile. He reports: “Development intelligence strategies such as automated dashboards are excellent tools to steer projects and ensure that agile teams are working effectively. In large organizations where there are many projects the physical space and governance needs make the use of whiteboards to track projects (e.g., taskboards, burndown charts) unfeasible. Management cannot be expected to attend ten or more daily meetings to understand if the projects responsible for their strategy execution are on track. A large insurance company found that by using IBM Rational Team Concert (RTC) dashboards they could easily see how well projects were progressing towards their release goals and if the agile practices that they had adopted were being followed correctly. By looking at the dashboards, they discovered that some teams were not writing stories effectively, nor concluding the iteration by either marking stories as being done or moving incomplete stories to the next iteration or to the product backlog. The dashboards also helped them get a handle on their technical debt. It was easy to view the defect trend for a single team or for the entire enterprise and understand if the teams were addressing quality throughout the projects or just towards the end of the release. The insurance company was also able to see whether the team was tracking impediments, performing retrospectives, and taking a few key actions from the retrospectives.”

Ambler, Scott W.; Lines, Mark (2012-05-31). Disciplined Agile Delivery: A Practitioner's Guide to Agile Software Delivery in the Enterprise (IBM Press) (Kindle Locations 8337-8348). Pearson Education. Kindle Edition. 
