anchor:chap-process-mgmt[]

=== Chapter 9: Process Management

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is in process as of May 27 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

==== Introduction to Chapter 9

What is "process?"

http://www.dictionary.com/browse/process[Dictionary.com] defines it as "a systematic series of actions directed to some end . . . a continuous action, operation, or series of changes taking place in a definite manner."

We've discussed xref:2.05.00-work-management[work management], which is an important precursor of process management. Work management is less formalized; a wide variety of activities are handled through flexible Kanban boards based on the simplest "process" of:

* To do
* Doing
* Done

Process management starts with the fundamental capability for coordinated work management, and refines it much further.



Process, in terms of "business process," has been a topic of study and professional development for many years. Toyota considers a clear process vision, or "target condition," to be the most fundamental objective in improving operations (<<Rother2010>>, chapters 5-6).  Designing processes, improving them, and using them to improve overall performance is an ongoing activity in most if not all organizations.

However, process can cause problems. Processes imply xref:queuing[queues], and in digital organizations this means invisible work in process. Organzational improvement approaches that encourage the formation of processes and associated metrics at all levels may therefore not be an effective model.

Nevertheless, process remains an important tool in the toolkit for organization design.


===== Chapter 9 overview

* Process management basics
 - BPM community
 - Process as a Mintzberg liaison mechanism

****
Sidebar: Can microservices eliminate most or all need for cross-team communication & liaison mechanisms?
****

* Function vs process

* Practice, discipline, capability vs process

* Process and execution (execution includes concern for resource)

* "Process" at Toyota (Rother)

****
Sidebar: Lessons from manufacturing, operations research, etc

Controversy of application to IT

Will this have been foreshadowed?
****

* Self-organizing (kanban) processes vs. formalized process frameworks.

* IT "process" frameworks (ITIL etc - also in appendix)

* Process in product-centric organizations

* Process antipatterns (should I do more with antipatterns in each chapter?)
 - Process proliferation
 - Process without execution model (demand management failure)

* SLAs and the service catalog
** Service-izing functions: pros and cons

****
Sidebar: Quality and Continuous Improvement
****

===== Chapter 9 learning objectives

* Describe a business process and how it crosses functions
* Describe the relationship between business process and business performance
* Describe the origins, purpose, and scope of ITIL and CMMI
* Identify the problems of process proliferation with respect to execution and demand
