=== Towards a theory of IT management
As we look forward, and consider the scale at which we are now operating, the challenges only seem to increase. Increasingly, we need to look to engineering and operations practices from other fields, and to math and science for useful theoretical tools.

Risk management, complex systems failures, how to safely manage combined human/technical systems - this is all well studied in domains like aerospace. We can't understand "change" management without better definitions of change and stability, concepts well studied in the quantitative sciences. No matter the safeguards, complex systems are prone to fail - but can we conceive of systems that can increase their stability through learning from their failures?

Finally, what do we even mean by complexity? What is the relationship between the merely complicated, the truly complex, and the absolutely chaotic? What do we need to understand about these various domains, to continue our journey of digital transformation?

Folk models = "sr. clinician's opinions" - Nancy Raymond

the problem of frameworks - folk applications of semantics

traditions of canon law (see chapter 11)

Optimizing across multiple constraints

Limits of iterative approaches ... missing higher order modes ...


* Reinertsen's critique of CC

What we can and cannot learn from simulations (AB Murray)
