== Section IV: Maturation

=== Section IV introduction

*Scenario*

You are now running one of the larger and more complex IT-based operations on the planet, with an annual IT budget of hundreds of millions or billions of dollars. You have thousands of programmers, systems engineers, and IT managers, with a wide variety of responsibilities.  IT is in your market-facing products and in your back-office operations. In fact, it's sometimes hard to distinguish the boundaries as your company transforms into a digital business.

Agile techniques remain important to you, but things are getting complex and you're testing the boundaries of what is possible. How can you operate at the scale you've achieved and still be Agile? As usual in life, you're finding that there are always tradeoffs. Decisions you made long ago come back to haunt you, security threats are increasing, and at your scale there's no escaping the auditors.

But you have great resources at your command, and you're as well positioned as any of your competitors to meet the challenges ahead. And in the end, that's all you need.

*Special section: The elaborated IT organization*
The laundry lists
supporting functions (sourcing...)

IVI
IT4IT

*Chapter 10: Security, Governance, Risk, and Compliance*

We need to cope with external forces (regulators, vendor partners, security adversaries, auditors) increasingly defining our options.

*Chapter 11: Enterprise Information Management*

We've been concerned with data, information, and knowledge since the earliest days of our journey. But at this scale, we have to formalize our approaches and understandings; without that, we will never capture the full value available with modern analytics and Big Data.

Looking inward, we need to measure this massive IT estate and understand it as an overall dynamic and complex system.

*Chapter 12: Arcihtecture and Portfolio*

We need to understand the big picture of interacting lifecycles, reduce technical debt and redundancy, and obtain better economies of scale. We need to define our investment strategy based on a sound understanding of both business needs and technology limitations.
